### ISSUE TITLE
Comment getMac256Hash

### ISSUE THREAD

**Issue by Demurgos** [OllieTerrance/SkPy#15]
Hi,
Could you help me understanding the code for [getMac256Hash](https://github.com/OllieTerrance/SkPy/blob/6416045809c3514f7069e22397cec665dac68887/skpy/conn.py#L549-632) ?

Does "mac256Hash" stands for [Hash-based message authentication code](https://en.wikipedia.org/wiki/Hash-based_message_authentication_code) ?
What does the `qw`, `CS` and `p` (as in `pClearText`) stand for ?
Why is it called `256` when you return 128 bits ? (4 int32 hex strings)

**Comment by OllieTerrance** [comment]
I'm not entirely sure how it all works, so have avoided cleaning it up too much (there may well be a much better way to do this in Python).  It is a form of HMAC-SHA256 though.

The JavaScript version in Skype for Web is rather obfuscated -- try searching for `sha256Auth` in [the main JS file](https://swx.cdn.skype.com/v/1.40.107/js/fullExperience.min.js).  There's a [C implementation for Pidgin here](https://github.com/EionRobb/skype4pidgin/blob/master/skypeweb/skypeweb_util.c#L121-L214), which is a bit more readable and has some comments on the process.

**Comment by Demurgos** [comment]
Ok, thank you for your quick answer. I'll take a look at it.

**Comment by Demurgos** [comment]
That's great.
I decided to automate the decompilation of SkypeWeb in [this repo](https://github.com/Demurgos/skype-web-reversed/tree/master/skype/latest/decompiled/fullExperience), do you know if there are other projects of this sort ?
I wrote a naive decompiler for requireJS. It should get all the define calls, but it's not respecting the scope so there are lots of missing parts. I'll try to fix it quickly (ie. find the `define`s and augment the scope while there are undefined variables).

**Comment by OllieTerrance** [comment]
I'm not aware of anything similar, but that does look pretty cool.  :+1:

(For the record, I've only had to poke around with Skype for Web's JavaScript for the reg token stuff -- everything else so far has just come from debugging network requests...)

**Comment by Demurgos** [comment]
Ok, I just discovered that there is no real tool to decompile JS files built with `requireJS` so I tried to build something. There are some scope issues, but it works pretty good here (especially, there are no nested `define`s). My biggest problem is that this file seems to be built by concatenating other bundles built with other tools.
Here is [what is remaining in the main file](https://raw.githubusercontent.com/Demurgos/skype-web-reversed/f9d36d0cf35033b77d9e4d1c9ba5d379f36e6c51/skype/latest/decompiled/fullExperience/__unresolved/fullExperience.min.js) after splitting the `requireJS` bundle. Each `require("~foo")` is a reference to an other file.

I know that once you have some basic logic you can derive anything from the network, but it might help to have a commented copy of the source code. What I would like in the end is to be able to unbuild this file and merge it with a previously commented file + add some documentation about the global behaviour of `Skype-Web`.
It could serve as some common resources for this module, Pidgin's implementation and also the JS package I'm planning to write.
