### ISSUE TITLE
Use SkyPy to check if user exists

### ISSUE THREAD

**Issue by mklimek** [OllieTerrance/SkPy#17]
Hello,

I'm wondering there's a way to check if given `username` exists without pass a password.
I'd like to use SkPy to verify a list of users and delete all "non-skype-user" from it.

Could you give me some hint?

Cheers!

**Comment by OllieTerrance** [comment]
There's no foolproof way of doing that.

You can't do anything useful here without authenticating, and even then you can't tell if a user exists or not from the API alone -- see [`SkypeContacts.user(id)`](http://skpy.t.allofti.me/api.html#skpy.user.SkypeContacts.user) (specifically, there's no way to tell the difference between a private profile, and one that doesn't exist).

**Comment by mklimek** [comment]
As I understand there's no chance to do that by SkyPy API and Skype API itself as well?

**Comment by OllieTerrance** [comment]
This is a limitation of the upstream web APIs, so will be a limitation of any libraries that use them.

(There may be a different way to detect what you're looking for, but I've yet to come across one.)

**Comment by demurgos** [comment]
Maybe you could try to use the avatars, they seem to not be restricted. I do not remember the exact syntax, but I think that it depends only on the username (or prefixed with the user resource type).

**Comment by OllieTerrance** [comment]
That still doesn't make any distinction between non-existent users, and users without a profile picture?

e.g. https://api.skype.com/users/dfgdfklgjdfkljgdsdfjhgjfklgjdfklg/profile/avatar

**Comment by demurgos** [comment]
Right, I thought that you would get a 404 error :/

**Comment by OllieTerrance** [comment]
The user API might be a start, as many users aren't private and will therefore return _something_*, but it'll be far from complete.  The Skype HTTP APIs are designed for a client and nothing more, so there isn't much in the way of flexibility.

---

\* A private or non-existent profile will look like this:
```python
>>> sk.contacts["sdkljsdlfjsdklfjsdlkf"]
SkypeUser(id='sdkljsdlfjsdklfjsdlkf', name=Name(), location=Location())
```
Any other fields present and it probably represents an actual user.
