### ISSUE TITLE
404 when calling setPresence + no endpoints returned

### ISSUE THREAD

**Issue by leondealmeida** [OllieTerrance/SkPy#22]
I'm consistently getting 404s on a machine running the library - to the extent I modified my code to not call setPresence. Here's one of the error occurrences:

```
Traceback (most recent call last):
  File "/opt/nagbot/code/run_bot.py", line 54, in <module>
    chat_id=chat_id
  File "/opt/nagbot/code/skype_bot/nagbot.py", line 14, in __init__
    super().__init__(user=username, pwd=password, tokenFile=token_file, autoAck=auto_ack)
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/main.py", line 183, in __init__
    super(SkypeEventLoop, self).__init__(user, pwd, msEmail, msPwd, tokenFile)
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/main.py", line 70, in __init__
    self.conn.getSkypeToken()
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/conn.py", line 262, in getSkypeToken
    self.login(user, pwd)
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/conn.py", line 404, in login
    self.getRegToken()
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/conn.py", line 543, in getRegToken
    self.endpoints["main"].config()
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/conn.py", line 601, in config
    "version": "908/1.30.0.128"}})
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/conn.py", line 215, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('404 response from PUT https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/2b9857e1-c9cb-4c78-9b94-b59a5d46c7f4/presenceDocs/messagingService', <Response [404]>)
```

One other thing I did notice is that the return from the 
```
endpointResp = self("POST", "{0}/users/ME/endpoints".format(self.msgsHost), codes=(200, 201, 404),
                    headers=headers, json={"endpointFeatures": "Agent"})
```
call, on  skpy/conn.py, lines 520-521, does not contain any data, and then the subsequent call to `endpointResp.json()` returns `[]`. This breaks `self.endpoints["main"] = SkypeEndpoint(self, endpointResp.json()[0]["id"])` on line 540 of that same file.

In order for the bot to work, I added a conditional that does not run line 540 if there is no length for `endpointResp.json()`. The bot is running with the latest git codebase, and using Python 3.5.2. Any help is appreciated.

**Comment by OllieTerrance** [comment]
Can't seem to reproduce with a test account, I always seem to get either a `Location` header or a response body.  Can you get a dump of the headers on the `endpointResp` request?  Just curious if there's a hint to another way of retrieving the endpoint...

Ideally the check on line 538 should be extended to check the contents of the body too.

**Comment by OllieTerrance** [comment]
Need more info to reproduce...  😞

**Comment by leondealmeida** [comment]
Sorry for the delay... I'm gathering the data right this moment.

**Comment by leondealmeida** [comment]
Attached is the login page contents when I get a raise due to missing token:

```
Traceback (most recent call last):
  File "/opt/nagbot/code/run_bot.py", line 54, in <module>
    chat_id=chat_id
  File "/opt/nagbot/code/skype_bot/nagbot.py", line 14, in __init__
    super().__init__(user=username, pwd=password, tokenFile=token_file, autoAck=auto_ack)
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/main.py", line 183, in __init__
    super(SkypeEventLoop, self).__init__(user, pwd, msEmail, msPwd, tokenFile)
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/main.py", line 70, in __init__
    self.conn.getSkypeToken()
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/conn.py", line 262, in getSkypeToken
    self.login(user, pwd)
  File "/opt/nagbot/venv/lib64/python3.5/site-packages/skpy/conn.py", line 396, in login
    raise SkypeApiException("Couldn't retrieve Skype token from login response", loginResp)
skpy.core.SkypeApiException: ("Couldn't retrieve Skype token from login response", <Response [200]>)
```

[loginpage.zip](https://github.com/OllieTerrance/SkPy/files/514918/loginpage.zip)

**Comment by leondealmeida** [comment]
:/

And then suddenly it started playing nice:

```
{'X-Content-Type-Options': 'nosniff', 'Content-Length': '2', 'ContextId': 'tcid=4906785045433939045,server=BN3SCH030022442', 'Date': 'Thu, 06 Oct 2016 22:50:33 GMT', 'Set-RegistrationToken': 'registrationToken=lotsofbase64datahere==; expires=1475880632; endpointId={d06fc436-3a9b-4fb7-beff-59de97d49321}', 'Location': 'https://bn2-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/%7Bd06fc436-3a9b-4fb7-beff-59de97d49321%7D', 'Cache-Control': 'no-store, must-revalidate, no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Pragma': 'no-cache'}
```

I was forced by Microsoft to use a single password for the account, both live and skype username (each had their own values). I'm not sure what's going on, but all seems to be working now - thanks for the support.

**Comment by OllieTerrance** [comment]
I'm assuming this is a Live-only account (that is, you signed up with an MS account, or created a new MS account in the process of creating a new Skype account), which gives you the `live:` username prefix.  Was this recent, or back when you could create a Skype account without an MS account?

> [loginpage.zip](https://github.com/OllieTerrance/SkPy/files/514918/loginpage.zip)

Looks like after submitting your username and password, you just got the login page back again without an error.  Normally, entering your email address in the username field and tabbing away causes the page to redirect over to the MS flow, so maybe there is (was?) some server-side magic to block Live logins.

> I was forced by Microsoft to use a single password for the account, both live and skype username (each had their own values).

Didn't know that was a thing -- I thought there was no Skype auth for Live-only accounts.  Certainly I can't seem to sign in through the user/pwd flow with my test account, presumably as it doesn't have a password...

Likewise, `Skype("live:<username>", "<password>")` doesn't work for me (`self.login(user, pwd)` is in the stack trace so I guess you are authing this way).  `Skype(msEmail="<email>", msPwd="<password>")` uses the MS account flow and should work regardless of Skype account password though.

**Comment by leondealmeida** [comment]
I was able to create a skype-only username after fiddling around (though that was tied to the MS account, I was able to log into skype using it) and was using it consistently. Then I hit a wall and when I went to check the account, MS had disabled it.

Going through that process I got the notification the password would be the same for both logins, and that I should use the same password for both. I still can't grasp what's the process behind all this.

Kicked off the bot yesterday, still running normally.

**Comment by OllieTerrance** [comment]
All rather strange.  They've already stopped creation of Skype-only accounts, so I suspect MS will eventually kill off user/pwd auth altogether, requiring everyone to sign in via Microsoft accounts...

But good to hear it's working now in any case.  👍
