### ISSUE TITLE
Drop Skype auth, make Microsoft auth default

### ISSUE THREAD

**Issue by OllieTerrance** [OllieTerrance/SkPy#25]
Looks like all logins, Microsoft account or not, now go via login.live.com.  To my amazement, Skype-only accounts can use `Skype(msEmail=<username>, msPwd=<password>)` out of the box.

**Comment by sanjaysi** [comment]
Thank you Ollie. I pulled the latest code and it is working fine now. You are awesome!

**Comment by OllieTerrance** [comment]
Excellent, this fixes #26 too.  🎉
