### ISSUE TITLE
Any change in authentication

### ISSUE THREAD

**Issue by sanjaysi** [OllieTerrance/SkPy#26]
Hi Ollie, thanks for the wonderful library. It works like charm.
Any change happened in the login module...getting following error since few hours.

File "C:\Python35\lib\site-packages\skpy\main.py", line 68, in __init__
    self.conn.readToken()
  File "C:\Python35\lib\site-packages\skpy\conn.py", line 297, in readToken
    raise SkypeAuthException("No token file specified")
skpy.conn.SkypeAuthException: No token file specified

**Comment by OllieTerrance** [comment]
Skype just changed the authentication model (see #25) -- does the latest commit fix it?

That said, the trace suggests you're not passing any args to the `Skype()` constructor.  Can you paste the full traceback (or at least how you're calling the library)?
