### ISSUE TITLE
Delete or edit throws exception

### ISSUE THREAD

**Issue by sanjaysi** [OllieTerrance/SkPy#27]
Following exception is thrown on edit or delete call even if the message content is present.
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\skpy\chat.py", line 370, in __getitem__
    return super(SkypeChats, self).__getitem__(key)
  File "C:\Python35\lib\site-packages\skpy\core.py", line 138, in __getitem__
    return self.cache[key]
KeyError: None

**Comment by OllieTerrance** [comment]
Please include some sample code and a full traceback (if that isn't already?) with HTTP debugging enabled (set `SKPY_DEBUG_HTTP=1` in your environment) to see the underlying API calls.

Assuming you mean editing/deleting a message, can't seem to reproduce here from master:

```python
>>> sk = Skype(...)
>>> c = sk.chats["19:<redacted>@p2p.thread.skype"]
>>> m = c.sendMsg("Test.")
>>> m.edit("Test...")
>>> m.delete()
>>>
```

What type of conversation are you working with -- cloud-only group (`19:<hash>@thread.skype`), converted group (`19:<hash>@p2p.thread.skype`), or 1-to-1 (`8:<user>`)?

**Comment by sanjaysi** [comment]
Hi Ollie, please find below the stack trace on setting the SKYPE_DEBUG flag:

<= [14/10 23:46:24] GET https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/None
{'params': {'view': 'msnp24Equivalent'}}
=> [14/10 23:46:24] 400
{'errorCode': 201, 'message': 'The resource URL is misformatted.'}
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\skpy\chat.py", line 370, in __getitem__
    return super(SkypeChats, self).__getitem__(key)
  File "C:\Python35\lib\site-packages\skpy\core.py", line 138, in __getitem__
    return self.cache[key]
KeyError: None

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "deletemsgs.py", line 26, in <module>
    msg.delete()
  File "C:\Python35\lib\site-packages\skpy\msg.py", line 279, in delete
    self.edit("")
  File "C:\Python35\lib\site-packages\skpy\msg.py", line 271, in edit
    self.chat.sendMsg(content, me, rich, self.clientId)
  File "C:\Python35\lib\site-packages\skpy\util.py", line 148, in chatObj
    return self.skype.chats[getattr(self, field)]
  File "C:\Python35\lib\site-packages\skpy\chat.py", line 372, in __getitem__
    return self.chat(key)
  File "C:\Python35\lib\site-packages\skpy\chat.py", line 408, in chat
    auth=SkypeConnection.Auth.RegToken, params={"view": "msnp24Equivalent"}).json()
  File "C:\Python35\lib\site-packages\skpy\conn.py", line 214, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('400 response from GET https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/None', <Response [400]>)
```

**Comment by OllieTerrance** [comment]
Looks like the API has stopped returning a separate message ID from its client ID.  🤔

Client ID appears to work in its place though.  Does `chat.sendMsg("", edit=msg.clientId)` work for you?

**Comment by sanjaysi** [comment]
`chat.sendMsg("", edit=msg.clientId) `throws following exception:

```
<= [15/10 01:22:50] POST https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:sanjay_at_skype/messages
{'json': {'content': '',
          'contenttype': 'text',
          'messagetype': 'Text',
          'skypeeditedid': '1476378019870',
          'skypeemoteoffset': None}}
=> [15/10 01:22:51] 400
{'errorCode': 201,
 'message': 'Either "startTime" or "startComposeTime"query string parameter '
            'must be provided'}
Traceback (most recent call last):
  File "deletemsgs.py", line 27, in <module>
    chat.sendMsg("", edit=msg.clientId)
  File "C:\Python35\lib\site-packages\skpy\chat.py", line 133, in sendMsg
    return self.sendRaw(editId=edit, messagetype=msgType, content=content, skypeemoteoffset=meOffset)
  File "C:\Python35\lib\site-packages\skpy\chat.py", line 78, in sendRaw
    auth=SkypeConnection.Auth.RegToken, json=msg).json().get("OriginalArrivalTime")
  File "C:\Python35\lib\site-packages\skpy\conn.py", line 214, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('400 response from POST https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:sanjay_at_skype/messages', <Response [400]>)
```

**Comment by OllieTerrance** [comment]
> Either "startTime" or "startComposeTime"query string parameter must be provided

Haven't seen either of those parameters before... 😞

Consulting Skype for Web on my account, it seems the current HTTP request body looks like this:

```json
{"content": "Test.",
 "messagetype": "RichText",
 "contenttype": "text",
 "Has-Mentions": "false",
 "imdisplayname": "Me",
 "clientmessageid": "1476476575754"}
```

For edits, `clientmessageid` is replaced by `skypeeditedid` (referencing the previous message's identifier).  This appears to still be in line with SkPy (minus the `Has-Mentions` key).

It would be useful to know if you see any different -- possibly there is a partial rollout that changes this behaviour.  To debug [Skype for Web](https://web.skype.com), open a developer console on the network tab, send or edit a message, and check the request body in the API call to:

```
POST https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:<user>/messages
```

(Chrome only shows the end of the URL, so it will just appear in the list as `messages`.  There will also be two requests -- first an `OPTIONS` pre-flight, then the actual `POST`, make sure to check the latter.)

**Comment by sanjaysi** [comment]
Now it is throwing following exception. It looks as though the endpoint is not received.: Do you want me to open a new issue?

```
<= [15/10 08:39:02] PUT https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/ad655093-7eb7-4b9f-8222-b19199788654/presenceDocs/messagingService
{'json': {'id': 'messagingService',
          'privateInfo': {'epname': 'skype'},
          'publicInfo': {'capabilities': '',
                         'nodeInfo': 'xx',
                         'skypeNameVersion': 'skype.com',
                         'type': 1,
                         'version': '908/1.30.0.128'},
          'selfLink': 'uri',
          'type': 'EndpointPresenceDoc'}}
=> [15/10 08:39:02] 404

```
```
{'errorCode': 729,
 'message': 'You must create an endpoint before performing this operation.'}
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\skpy\main.py", line 63, in __init__
    self.conn.readToken()
  File "C:\Python35\lib\site-packages\skpy\conn.py", line 283, in readToken
    raise SkypeAuthException("No token file specified")
skpy.conn.SkypeAuthException: No token file specified
```

**Comment by OllieTerrance** [comment]
> ```
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\skpy\main.py", line 63, in __init__
    self.conn.readToken()
  File "C:\Python35\lib\site-packages\skpy\conn.py", line 283, in readToken
    raise SkypeAuthException("No token file specified")
skpy.conn.SkypeAuthException: No token file specified
```

I need the full stacktrace, that exception is an internal one (it's caught at main.py:64 if you authed without a token file).  You should have a _During handling of the above exception, another exception occurred_ part to it.

In any case, calling `sk.conn.getRegToken()` should provide you with a new endpoint.

**Comment by sanjaysi** [comment]
Hi Ollie, I added the following code in chat.py and it is working fine now:

```
        msg["messagetype"] = "RichText"
        msg["Has-Mentions"] = "false"
```

**Comment by OllieTerrance** [comment]
Message type is set based on the `rich` parameter of [`sendMsg()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChat.sendMsg), defaults to `Text` if not `RichText`.  I'll get the mentions parameter in there too -- was hoping to add a mention helper, but the UI for creating mentions on Skype for Web seems to have disappeared when I want to test it...

**Comment by OllieTerrance** [comment]
Mentions added in 4b7c281, does that get things working?

**Comment by sanjaysi** [comment]
Tested with few messages. It is working now.

**Comment by OllieTerrance** [comment]
👍
