### ISSUE TITLE
Receiving messages older than 30 days

### ISSUE THREAD

**Issue by sanjaysi** [OllieTerrance/SkPy#28]
Hi Ollie, I see that when we repeatedly call getMsgs(), it gets messages only for last 30 days. Is there a way to specify the duration (start and end dates) for which the messages can be returned?

**Comment by OllieTerrance** [comment]
Already passing `"startTime": 0` to retrieve everything, so this is probably a server-side limit.  Skype for Web seems to cut off at 30 days too.

**Comment by sanjaysi** [comment]
We can update past message if `skypeeditedid `is known. I explored the tables present in the main.db but could not find `skypeeditedid `field. Is it a calculated value? If yes, how it is done?

**Comment by OllieTerrance** [comment]
`skypeeditedid` is just the `clientmessageid` of the original message.  So when a new message is created, the client uses its local timestamp as the identifier.  Any edits/deletes of that message reuse that identifier as `skypeeditedid` to link the two.

**Comment by sanjaysi** [comment]
Thanks Ollie. I don't know whether you explored the main.db which has all the attributes. However when I compare the timestamp with skypeditedidfield they do not match. Since skype api does not give data for more than 30 days, we can use the ids from main.db which stores old data. But I am not able to get the id that matches skypeeditedidfield.

**Comment by OllieTerrance** [comment]
I haven't looked at main.db, but as it's a desktop client it probably doesn't use all the same APIs...

Skype for Web used to have a second message ID (which seems to have been removed as noted in #27).  It may be the case that the desktop clients use their own ID system too.

**Comment by sanjaysi** [comment]
Thanks Ollie.
