### ISSUE TITLE
Need a little help i'm confused.

### ISSUE THREAD

**Issue by tryzombie501** [OllieTerrance/SkPy#35]
I'm trying to write something that waits for messages and then responds, But i am having problems doing that could anyone here show me how to write that? Please?

**Comment by OllieTerrance** [comment]
The example in the readme does just that (listens for "ping" and responds "pong"):

```python
from skpy import SkypeEventLoop, SkypeNewMessageEvent
class SkypePing(SkypeEventLoop):
    def __init__(self):
        super(SkypePing, self).__init__(username, password)
    def onEvent(self, event):
        if isinstance(event, SkypeNewMessageEvent) \
          and not event.msg.userId == self.userId \
          and "ping" in event.msg.content:
            event.msg.chat.sendMsg("Pong!")
```

**Comment by tryzombie501** [comment]
I've tried that example i can't get it to work, It's most likely my fault i'm new to python but i know some other things such as php and vb.

I'll post my py file if needed cause i don't want to take up too much of your time.

**Comment by OllieTerrance** [comment]
I'll need something more than "can't get it to work"...  code and output would be good.

Does a traceback occur?  Does the library act differently to the server?  Do the problems lie with sending the message, receiving the message, authenticating in the first place, something else?

**Comment by tryzombie501** [comment]
I'm not getting error's again me being stupid as usual i'll just show you what i have in the py file so you can tell me what i'm doing wrong

```
`from skpy import Skype
sk = Skype("username", "password") # connect to Skype

from skpy import SkypeEventLoop, SkypeNewMessageEvent
class SkypePing(SkypeEventLoop):
    def __init__(self):
        super(SkypePing, self).__init__(username, password)
    def onEvent(self, event):
        if isinstance(event, SkypeNewMessageEvent) \
          and not event.msg.userId == self.userId \
          and "ping" in event.msg.content:
            event.msg.chat.sendMsg("Pong!")


```
`

**Comment by tryzombie501** [comment]
You can close, Like i said it was me being stupid.

**Comment by tryzombie501** [comment]
I'm assuming there is something i can call to tell the other user i am typing right? Had to ask cause i wanted to display [username] is typing before sending a message

**Comment by OllieTerrance** [comment]
Yep: [`SkypeChat.setTyping()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChat.setTyping)
