### ISSUE TITLE
Live Account Not Working

### ISSUE THREAD

**Issue by firecurious** [OllieTerrance/SkPy#36]
I'm trying to help my friend run a Skype bot. It turns out that sometime around three months ago, Microsoft changed Skype and the website to only allow the creation of live accounts. When trying to sign into such an account via SkPy, it throws an error stating that the account doesn't exist, even though it's possible to sign into it through web Skype.

We're just using the standard ping/pong snippet from the docs, which is working for me for a normal Skype account with its own username. Here is the error:

```skpy.core.SkypeAuthException: (u"That Microsoft account doesn't exist. Enter a different account or get a new one.", <Response [200]>)```

I get the same error running it from my system. Are live accounts broken right now in SkPy? I checked through the issues and couldn't find any way around this.

**Comment by OllieTerrance** [comment]
Can't reproduce with my test Live account, auth and tests appear to be working.

Are you using a release version (i.e. from pip) or the latest repo code?  It looks like I'm overdue a release, there's some auth changes that haven't gone out yet, though I don't think that would affect this.

The repo code does now provide [`SkypeLiveAuthProvider.checkUser(user)`](https://skpy.t.allofti.me/internal.html#skpy.conn.SkypeLiveAuthProvider.checkUser), which does the same test as when you enter your username on the login page, to see if the account exists or not.

```python
>>> from skpy import SkypeConnection, SkypeLiveAuthProvider
>>> prov = SkypeLiveAuthProvider(SkypeConnection())
>>> prov.checkUser("you@live.co.uk")
True
```

**Comment by OllieTerrance** [comment]
@firecurious: Still an issue?  Have you tried the above?

**Comment by OllieTerrance** [comment]
Can't reproduce... 😞
