### ISSUE TITLE
FileMessage fails with empty content

### ISSUE THREAD

**Issue by Xcelled** [OllieTerrance/SkPy#38]
I think this message was edited/deleted.

`SkypeImageMsg(id='14829808000', type='RichText/UriObject', time=datetime.datetime, clientId='900182', userId='blarp', chatId='8:blurp', content='')`

The raw dict for it is:

```
{'version': '1482980188000', 'type': 'Message', 'originalarrivaltime': '2016-12-29T02:56:28.003Z', 'from': 'https://bn2-client-s.gateway.messenger.live.com/v1/users/ME/contacts/', 'content': '', 'skypeeditedid': '9002182', 'composetime': '2016-12-29T02:56:28.003Z', 'messagetype': 'RichText/UriObject', 'id': '1482980188000', 'conversationLink': 'https://bn2-client-s.gateway.messenger.live.com/v1/users/ME/conversations/'}
```

calling html on it results in

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/SkPy-0.0.0-py3.5.egg/skpy/msg.py", line 502, in html
AttributeError: 'NoneType' object has no attribute 'urlFull'
```

**Comment by OllieTerrance** [comment]
Indeed, empty content means the message was deleted, so there is no image to parse out of it.

I think there's a few places now where it would be nice to throw some derivative of `SkypeException` instead of things like `AttributeError`.

**Comment by OllieTerrance** [comment]
I think actually it makes sense to return an empty string for `html` here -- the message is effectively deleted, and the upstream API returns an empty string too.

**Comment by Xcelled** [comment]
What about also adding a deleted flag? Or is this something best done by the consumer of the lib?

**Comment by OllieTerrance** [comment]
If you need that, you can just use `msg.html == ""`.  I guess it wouldn't hurt to add a `isDeleted` property, though that's all it would do...

**Comment by Xcelled** [comment]
That's a bit more intuitive for a consumer, I think. Plus, if anything changes protocol-wise in the future, it'll help to encapsulate the change.

**Comment by OllieTerrance** [comment]
Ok, a92d209 adds [`SkypeMsg.deleted`](https://skpy.t.allofti.me/api.html#skpy.msg.SkypeMsg.deleted).  🙂
