### ISSUE TITLE
call forwarding

### ISSUE THREAD

**Issue by d2-d2** [OllieTerrance/SkPy#40]
Hey there, is it possible to setup call forwarding (a.k.a. call transfers) with this API?

**Comment by OllieTerrance** [comment]
No such APIs within SkPy.  If what you want can be done within [Skype for Web](https://web.skype.com), then potentially it can be implemented here too.  I think all the calling stuff requires a browser plugin, unless you refer to configuring stuff within your account, in which case that's (currently?) out of scope here.

**Comment by d2-d2** [comment]
OK thanks.

**Comment by OllieTerrance** [comment]
I'll close this for now -- it may be possible to add some account management features, but would require some investigation over how we authenticate to / get data from the portal pages.
