### ISSUE TITLE
Can't send msg

### ISSUE THREAD

**Issue by ya-888** [OllieTerrance/SkPy#42]
Hi all!

I have a problem with sending message by this module. I write code like at example, but it does not work. I created a new account on skype and added to my contacts list - live:8584067c9701be5c, because for old contacts in my contact list i can't send msg too. And if i will not put tokenFile param into Skype init i can't login by my acc, but it is another story':). So look:

`sk = Skype(login, get_pass(), tokenFile=".tokens-fred.2")  # connect to Skype`
`ch = sk.contacts['live:8584067c9701be5c'].chat`
`ch.sendMsg('hello')`

And i get the error:

> Traceback (most recent call last):
  File "%user_path%/bot/bot_main.py", line 88, in <module>
    ch.sendMsg('hello')
  File "%user_path%\lib\site-packages\skpy\chat.py", line 140, in sendMsg
    "Has-Mentions": mentions, "skypeemoteoffset": meOffset})
  File "%user_path%lib\site-packages\skpy\chat.py", line 81, in sendRaw
    auth=SkypeConnection.Auth.RegToken, json=msg).json().get("OriginalArrivalTime")
  File "%user_path%\lib\site-packages\skpy\conn.py", line 215, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
SkypeApiException: ('400 response from POST https://client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:live:8584067c9701be5c/messages', <Response [400]>)
Uncaught exception

Thanks for all and best regards

**Comment by OllieTerrance** [comment]
Hi, please set `SKPY_DEBUG_HTTP=1` in your environment and try it again -- this will output the underlying requests to Skype's servers, so please include the request and response for the 400 error above.  Are you able to retrieve messages from the conversation ([`SkypeChat.getMsgs()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChat.getMsgs)) or does that fail too?

> And if i will not put tokenFile param into Skype init i can't login by my acc

As in, you can't login at all without a token file, but can if you choose to write one?  (As opposed to loading an existing one, which would have required a successful login without a token file before.)

**Comment by ya-888** [comment]
[endpoint_error.txt](https://github.com/OllieTerrance/SkPy/files/763003/endpoint_error.txt)
So, i attached a file with stacktrace of the error. It is problem with endpoint. I can skip this error if i will comment out
`if endpoint:`
    `    endpoint.config()`
    `    self.endpoints["main"] = endpoint`
    `    self.syncEndpoints()`
this code and then i can get a token and connection. And then i be able to retrieve messages from the conversation (SkypeChat.getMsgs()) by this token. But i can't send message.
P.S. Second question about connect only with tokenFile param closed :+1: )

**Comment by OllieTerrance** [comment]
So I think this part is interesting:

```
<= [09/02 11:01:03] POST https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints
{'json': {'endpointFeatures': 'Agent'}}
=> [09/02 11:01:05] 200
[{u'id': u'2cd7916c-4472-7ac0-d06e-7349d13392c1',
  u'isActive': True,
  u'networks': [],
  u'policies': {},
  u'subscriptions': [{u'channelType': u'TcpSocket',
                      u'conversationType': 0,
                      u'eventChannel': u'',
                      u'eventServiceName': u'',
                      u'id': 0,
                      u'interestedResources': [u'/abch',
                                               u'/v1/threads/ALL',
                                               u'/v1/users/ME/conversations/ALL/messages',
                                               u'/v1/users/ME/conversations/ALL/properties',
                                               u'/v1/users/ME/contacts/ALL'],
                      u'packageSid': u'',
                      u'template': u'',
                      u'type': u'Subscription',
                      u'xuid': u''}],
  u'type': u'Endpoint'}]
<= [09/02 11:01:05] PUT https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints/2cd7916c-4472-7ac0-d06e-7349d13392c1/presenceDocs/messagingService
{'json': {'id': 'messagingService',
          'privateInfo': {'epname': 'skype'},
          'publicInfo': {'capabilities': '',
                         'nodeInfo': 'xx',
                         'skypeNameVersion': 'skype.com',
                         'type': 1,
                         'version': '908/1.30.0.128'},
          'selfLink': 'uri',
          'type': 'EndpointPresenceDoc'}}
=> [09/02 11:01:05] 404
{u'errorCode': 729,
 u'message': u'You must create an endpoint before performing this operation.'}
```

We try to create an endpoint for you, which returns 200 success rather than 201 created, suggesting you already have one.  But the response only contains a different endpoint -- it's a TcpSocket type so presumably you were running a desktop/mobile client on the same account?  The configure call tries to configure that endpoint rather than the one we want.  🤔

Can you try it again but also printing out the headers, specifically for the call to `POST https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints`?

Until I can improve the debug code, you can add this to [conn.py](https://github.com/OllieTerrance/SkPy/blob/master/skpy/conn.py#L116-L121):

```diff
diff --git a/skpy/conn.py b/skpy/conn.py
index de1fcdd..58df16c 100644
--- a/skpy/conn.py
+++ b/skpy/conn.py
@@ -116,4 +116,5 @@ class SkypeConnection(SkypeObj):
         if os.getenv("SKPY_DEBUG_HTTP"):
             print("=> [{0}] {1}".format(datetime.now().strftime("%d/%m %H:%M:%S"), resp.status_code))
+            print(pformat(dict(resp.headers)))
             try:
                 print(pformat(resp.json()))
```

**Comment by ya-888** [comment]
[endpointResp_header.txt](https://github.com/OllieTerrance/SkPy/files/763535/endpointResp_header.txt)
 i attached a file with headers which you mybe want. Because error raise in other method: endpoint.config(). And your print do not work. So i found, that there was not endpoint into token header and content is empty too.

**Comment by OllieTerrance** [comment]
It seems you're not given an endpoint at all.  🙁  I'm not sure what the correct behaviour is here as I haven't come across this with my test accounts before.  The next step would be to compare with Skype for Web and see how that handles this case, if you're up for the challenge...

Sign in at https://web.skype.com with DevTools open on the Network tab, and look for a `POST` request to `/v1/users/ME/endpoints` (either from `client-s.gateway.messenger.live.com`, or a subdomain like `db1-client-s.gateway.messenger.live.com`) -- check if the response differs from what SkPy gives you.  I'll also need to know what other requests it makes to get an endpoint.

Unfortunately there's a lot of cruft and noise from analytics and other non-important requests going on.  If you're using Chrome, here's a filter string to cut some of it out:

```
-method:OPTIONS -domain:browser.pipe.aria.microsoft.com -domain:trouter.io
```

**Comment by ya-888** [comment]
Hi!

Exuse me for delay, week-ends :)

I investigated response of web skype and found some information. So, look at the pictures:
1)It was the error to get the endpoint:
![ce5ba13e0bbd3aadb2db10e3a0641653](https://cloud.githubusercontent.com/assets/1596356/22875412/98586502-f1dc-11e6-9836-e46619516066.png)
Error text with hint:
![f091011cfadde022f8789bec1250c882](https://cloud.githubusercontent.com/assets/1596356/22875413/98596eb6-f1dc-11e6-9a99-820ac03cf11c.png)
And location:
![a6402060ecd9f62b8a0f18397a195ab9](https://cloud.githubusercontent.com/assets/1596356/22875411/98570b58-f1dc-11e6-917f-e620cecbff3a.png)
I think it is answer to my problem. Can you check it, please?

**Comment by OllieTerrance** [comment]
Ok, so that's the expected behaviour -- you get your endpoint in the registration token, and you get sent to a different cloud host.  Both of these cases [should be handled](https://github.com/OllieTerrance/SkPy/blob/master/skpy/conn.py#L716-L731), but this call in SkPy is giving you a different result in the first place.  Presumably the request body still only includes `endpointFeatures = Agent` as it does in SkPy?

If you've used Skype for Web (or just signed in with the corresponding Microsoft account) on that device/browser before, it may be caching some credentials and altering the login flow, so it _may_ perform differently if you clear your cookies / go incognito (though I am doubtful).

**Comment by ya-888** [comment]
Hey, i investigated network log again and found another responce with endpoint. First responce with OPTION method and had 200 return code like in SkPy without endpoint data. And after, the second responce had return code 404 and message about "Location" parameter. Look attached zip wtih .har log file( [try ](https://toolbox.googleapps.com/apps/har_analyzer/?lang=en) this resource, Please, change it to .har format, because github have not wanted to attach .har file and in zip too o_O)

[web.skype.com.txt](https://github.com/OllieTerrance/SkPy/files/770825/web.skype.com.txt)

**Comment by ya-888** [comment]
Thank you a lot! I resolved problem and using module now. :1st_place_medal:

**Comment by OllieTerrance** [comment]
Oh?  🙂  What was the solution in the end?
