### ISSUE TITLE
live account not working

### ISSUE THREAD

**Issue by cheekeykane** [OllieTerrance/SkPy#43]
ok so i've been trying to make a basic skype bot for a while with a code similar to the ping/pong snippet from the docs.
i can log into the live accounts i made on skype in my browser, but it ends up with skpy.core.SkypeAuthException: (u"That Microsoft account doesn't exist. Enter a different account or get a new one.", <Response [200]>)
here is the code if you need it https://paste.kde.org/po0ay3f7u

**Comment by OllieTerrance** [comment]
You should be using your Microsoft account email/phone as the username (i.e. whatever you use to sign in at https://web.skype.com or https://account.microsoft.com), not the derived Skype username.

**Comment by OllieTerrance** [comment]
Hopefully resolved now...
