### ISSUE TITLE
Login fails (response says you need javascript)

### ISSUE THREAD

**Issue by lassic** [OllieTerrance/SkPy#44]
Hi @OllieTerrance,
Seems like an amazing effort on this, I wanted to try it out.

I'm currently getting an error page on login (lack of javascript?).
Are you aware of that? Any chance you're still working on this?

Login response content is below:

```<html><head><noscript>JavaScript required to sign in<meta http-equiv="Refresh" content="0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033"/></noscript><title>Continue</title><script type="text/javascript">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload="javascript:DoSubmit();"><form name="fmHF" id="fmHF" action="https://account.live.com/identity/confirm?ru=https://login.live.com/login.srf%3flc%3d1033%26sf%3d1%26id%3d293290%26tw%3d18000%26fs%3d0%26ts%3d-1%26sec%3d%26mspp_shared%3d1%26seclog%3d10%26claims%3d%26wa%3dwsignin1.0%26wp%3dMBI_SSL%26ru%3dhttps://lw.skype.com/login/oauth/proxy%253fclient_id%253d578134%2526site_name%253dlw.skype.com%2526redirect_uri%253dhttps%25253A%25252F%25252Fweb.skype.com%25252F%26contextid%3d04BE3B5D88BB7F54&mkt=EN-US&uiflavor=web&id=293290&uaid=e90d9bd1ae5651536f7a2eec0973805c" method="post" target="_top"><input type="hidden" name="ipt" id="ipt" value="DaPp2!wBwkL9LL!ft0IGD7JIZxRZEX8J9v3eXaoknoP6s8oVyAjKwhkCbDyK*slSLmOA*zU20xRzSK2u8JorfuHEFH3pMoMVakvOGolU0mAdYV6FI!HiOrEPJ8Cebb1ToJO91CiOU*VtEnm!2XvWyPuWKv1pfBa4wl8s5NYTWKaPq0TGo3hp6satWYlUvB1!DEzMHgEc9rKuC7Fl!m03jF8YHTOj3aFwkO*5wq0sy0GJCwEwCLxFD*!Wqwq2w9A1t1XsaiyeV8OWFgOveSt1HdWSXGR2gcvwfyBlF6oPaH8ZVjVSXf7J8EweEYiV6q8RJsMnsI4WgLnFBssU8p3J6wc1lY4TjSDSjtkv*Li2VaAKsTFRfqE2fsvIcdRyqOyhXJPksXfFhK*kedtHTiXw5LoWXhNPcPHp6z0RWSN70N4*dR6eFSwdL7tp4CFqaCF56fA7pV5EcjklGyNmtMpIuBH137UXV1DcRUOeLP9tJWn*"></form></body></html>```

**Comment by OllieTerrance** [comment]
The JavaScript warnings are aimed at browsers, we make the API calls ourselves so that doesn't apply.

What step in the login flow is this?  It looks suspiciously like a two-factor page (judging by `https://account.live.com/identity/confirm`) -- two-factor isn't currently supported due to the rather silly hoops required to jump through.

**Comment by lassic** [comment]
I tried with a different account an it worked.
I suspect the first account failed since it detected an irregular login pattern (I had that account singed in from a different network).

Thanks for the quick response!
