### ISSUE TITLE
event.msg.plain() yields TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by Nothing4You** [OllieTerrance/SkPy#48]
Hey there,

I have recently updated my skpy from 0.6 to 0.7 and I started running into this problem.
I'm using Python 3.6.0.
```
2017-03-06 07:47:06,102 - ERROR - Exception
Traceback (most recent call last):
  File "./run.py", line 22, in onEvent
    logging.debug("text.plain(): " + str(text.plain()))
TypeError: 'str' object is not callable
```
I'm basically trying to use `event.msg.plain()` (`text = event.msg`) in `onEvent` in a `SkypeEventLoop` and it fails with a really weird error message.

By adding some debug output to msg.py I was able to verify that plain() is executed completely without any issues, however, it's beyond my understanding where this error could originate.

For now I have downgraded back to 0.6 since that version is working fine for me.

**Comment by Nothing4You** [comment]
d317279ab3533d12847ed79b1c51891989266b6a is the first bad commit
commit d317279ab3533d12847ed79b1c51891989266b6a
Author: Ollie Terrance <ollie.terrance@live.co.uk>
Date:   Tue Nov 8 23:21:52 2016 +0000

    Make plain content method a SkypeTextMsg property

:040000 040000 dc987578a6f2ce86c373c50f80090d383b9e48a4 7038c53e98a23769826755630a974e68446f1158 M      skpy

**Comment by OllieTerrance** [comment]
Yes, [`SkypeTextMsg.plain`](https://skpy.t.allofti.me/api.html#skpy.msg.SkypeTextMsg.plain) is a property now (as is [`SkypeTextMsg.markup`](https://skpy.t.allofti.me/api.html#skpy.msg.SkypeTextMsg.markup)), for consistency with other classes.

The API is liable to change for now -- there may be some more refactoring before a 1.0 release.
