### ISSUE TITLE
This error is normal?

### ISSUE THREAD

**Issue by maiconbaumx** [OllieTerrance/SkPy#53]
![screen shot 2017-04-05 at 10 44 59](https://cloud.githubusercontent.com/assets/15946206/24708414/234e1b7e-19ed-11e7-975c-14b67b817ca9.png)

**Comment by leondealmeida** [comment]
I used to get those when I was accessing the Skype account from two different IPs (one from my machine, one from the AWS instance).

**Comment by maiconbaumx** [comment]
Right... Make sense, I'm testing from my computer and from an EC2 on AWS.
Thank you!

**Comment by OllieTerrance** [comment]
Yeah, MS will likely flag you if they see your account accessed from multiple locations, particularly when previously unseen, or spanning multiple regions.

I'll go ahead and close this issue, unless it relates specifically to actions in SkPy (in which case please elaborate and we can take a closer look).
