### ISSUE TITLE
Callback working but posting message on response fails with 404

### ISSUE THREAD

**Issue by ArBohe** [OllieTerrance/SkPy#58]
Callback working but posting message on response fails with 404

### Account type

Live (Microsoft) Account

### Conversation details

1 to 1 conversation (response part to a received message)

### Steps to reproduce

I use your plain vanilla example from the doc for callback:

```
class SkypePing(SkypeEventLoop):
    def onEvent(self, event):
        if isinstance(event, SkypeNewMessageEvent) and not event.msg.userId == self.userId and "ping" in event.msg.content:
            event.msg.chat.sendMsg("Pong!")
```

Subscription works perfectly, I send a "ping" message to the skype account, it captures it.

Then on: event.msg.chat.sendMsg("Pong!"), it fails with 
SkypeApiException: ('404 response from GET https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/2:xxxxxxxx', <Response [404]>)

The trace (below) show the reason for this 404 is the conversation is not found. 
interrestingly enough, in the receipt acknoledging the start of the conversation (the ping) the conversation link is u'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/2:xxxxxxxxxxxxxx' where xxxxxxxxx is in fact xxxxxxxxx@yyyy.com.
Later, in the "pong" being sent the conversation the url is : https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/2:xxxxxxxxxxxxxx' where xxxxxxxxx is this time xxxxxxxxx  (without the @yyyy.com). Could it be that?

### Result or traceback

                     u'resource': {u'ackrequired': u'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/ALL/messages/1492900657077/ack',
                                   u'composetime': u'2017-04-22T22:37:37.077Z',
                                   u'content': u'ping',
                                   u'contentformat': u'FN=MS%20Shell%20Dlg; EF=; CO=0; CS=0; PF=0',
                                   u'conversationLink': u'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/2:xxxxxxxxxxxxxx',
                                   u'from': u'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/contacts/2:xxxxxxxxxxxxx',
                                   u'id': u'1492900657077',
                                   u'isactive': False,
                                   u'messagetype': u'Text',
                                   u'originalarrivaltime': u'2017-04-22T22:37:37.077Z',
                                   u'origincontextid': u'0',
                                   u'type': u'Message',
                                   u'version': u'1492900657077'},
                     u'resourceLink': u'https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/2:xxxxxxxxxxxx/messages/1492900657077',
                     u'resourceType': u'NewMessage',
                     u'time': u'2017-04-22T22:37:37Z',
                     u'type': u'EventMessage'}]}

```
<= [23/04 00:37:37] GET https://db5-client-s.gateway.messenger.live.com/v1/users/ME/conversations/2:xxxxxxxx
{'params': {'view': 'msnp24Equivalent'}}
=> [23/04 00:37:37] 404
{'Cache-Control': 'no-store, must-revalidate, no-cache',
 'Content-Length': '67',
 'Content-Type': 'application/json; charset=utf-8',
 'ContextId': 'tcid=1119067422058744749,server=DB5SCH101121543',
 'Date': 'Sat, 22 Apr 2017 22:37:37 GMT',
 'Pragma': 'no-cache',
 'StatusText': 'Failure due to: ConversationNotFound.'}
{u'errorCode': 730, u'message': u'Failure due to: ConversationNotFound.'}
```

**Comment by ArBohe** [comment]
I was right :)
I force-added the @yyyy.com in the chat.py (line 428) and it works like a charm.
The question now is: why does it drop the extension @yyyy.com from the conversationLink ???

**Comment by OllieTerrance** [comment]
I've yet to see a user with type `2` -- Skype for Business?

Dropping the domain is probably down to [this parsing of conversation URLs](https://github.com/OllieTerrance/SkPy/blob/master/skpy/util.py#L69-L83).

**Comment by ArBohe** [comment]
yup, Skype for Business!
So there you have it: if type 2 => keep the domain!

**Comment by OllieTerrance** [comment]
Arguably the regex shouldn't be trying to enforce a format at all, we don't know what other contact types might show up.
