### ISSUE TITLE
Error with ch.sendMsg

### ISSUE THREAD

**Issue by Derpolino** [OllieTerrance/SkPy#6]
> ch.sendMsg("Salut !")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "skpy\chat.py", line 157, in sendMsg
    return self.sendRaw(editId=edit, messagetype=msgType, content=content, skypeemoteoffset=meOffset)
  File "skpy\chat.py", line 110, in sendRaw
    clientTime = int(clientDate.timestamp() * 1000)
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

**Comment by OllieTerrance** [comment]
Good catch, looks like `datetime.timestamp()` isn't available on older versions of Python.
