### ISSUE TITLE
How to get renamed contact name

### ISSUE THREAD

**Issue by vsflur** [OllieTerrance/SkPy#60]
I had been rename the contact in skype, but when i call skype.contacts[].name, it is not renamed

**Comment by OllieTerrance** [comment]
You can't rename contacts in Skype for Web, and I'm not sure if custom names from desktop apps actually make it there either.  If you've already retrieved the contact, you may be able to refresh it by clearing the cache (`sk.contacts.cache.clear()`), or failing that by recreating the session, but I suspect it just won't be aware of them.

**Comment by kbulygin** [comment]
I use Skype for Linux and Skype for Android. Custom names are synced between the apps. To access them with SkPy:

```python3
from skpy import Skype
sk = Skype()
sk.conn.liveLogin(...)
userid = ...
raw = sk.contacts[userid].raw
if raw['display_name_source'] == 'user_edits':
    print('Custom name:', raw['display_name'])
```

Make sure that `sk.contacts.user(userid)` is not used before `sk.contacts[userid]`: otherwise, the user gets cached with limited data (without `display_name`).
