### ISSUE TITLE
can't get all messages from the chats

### ISSUE THREAD

**Issue by ostrowsky** [OllieTerrance/SkPy#62]
Hi! I'm trying to use skypy in order to receive llast messages from all the chats with my contacts running this code:
from skpy import *
from getpass import getpass
contacts = []
sk = Skype(tokenFile=".tokens-ostrowsky_")
source_contacts = sk.contacts
for contact in source_contacts:
    contacts.append("8:"+ str(contact.id))
print(contacts)
for contact in contacts:
    chat = sk.chats.chat(contact).getMsgs()
    if chat:
        print(chat[0], '\n')

 I'm not getting messages from all the chats but only 3 of them and after that this such traceback:

Traceback (most recent call last):
  File "C:/Users/Марина/Documents/Parcer-master/SkypeParcer.py", line 24, in <module>
    chat = sk.chats.chat(contact).getMsgs()
  File "C:\Python\lib\site-packages\skpy\chat.py", line 429, in chat
    auth=SkypeConnection.Auth.RegToken, params={"view": "msnp24Equivalent"}).json()
  File "C:\Python\lib\site-packages\skpy\conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('404 response from GET https://co4-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:evgen375291362177', <Response [404]>)

Process finished with exit code 1

Can you please help me to understand what is the problem?

**Comment by OllieTerrance** [comment]
Possible dupe of #41, though that seemed to be specific to bots.

You missed most of the information requested in the issue template:
* Skype or Microsoft account?
* Is this reliably reproducible?

Also:
* Is it always the same contacts that succeed/fail?
* Do you already have an open conversation with them?

Also also: you can just use the `contact.chat` property rather than `sk.chats["8:" + contact.id]`.

**Comment by ostrowsky** [comment]
1.Account Skype
2.This is reliably reproducible
3. Always succeed the same 3 contacts and after programm fails.
4.I have recently opened conversation with them and with some other contacts from wich I can't get messages

**Comment by ostrowsky** [comment]
And besides  if I try to change user and password in order to see how the programm runs under another account I get this:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\main.py", line 67, in __init__
    self.conn.readToken()
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 286, in readToken
    raise SkypeAuthException("No token file specified")
skpy.core.SkypeAuthException: No token file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/user/Documents/Parser/SkypeParcer.py", line 20, in <module>
    sk=Skype("anna.freelanser", "HfrbYfYt,t919")
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 264, in getSkypeToken
    self.liveLogin(user, pwd)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 363, in liveLogin
    self.getRegToken()
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 423, in getRegToken
    endpoint.config()
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 866, in config
    "version": "908/1.30.0.128"}})
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('403 response from PUT https://db5-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/{b178610e-557f-4fea-a8f6-b2ee26bcdbc1}/presenceDocs/messagingService', <Response [403]>)

Process finished with exit code 1

**Comment by OllieTerrance** [comment]
Try setting `SKPY_DEBUG_HTTP=1` in your environment to print the actual API response, or try-catch the exception and read the response `text` or `json`.  The 403 is rather generic, but the text may be more helpful.

**Comment by ostrowsky** [comment]
Where should I set SKPY_DEBUG_HTTP=1? Added it to the script but haven'got API response.

**Comment by OllieTerrance** [comment]
It's an environment variable, not a Python variable, though you may be able to inject it into `os.environ`.  The correct way is to start your script in a shell with that variable set.  Assuming a command prompt on Windows:

```
> set SKPY_DEBUG_HTTP=1
> python SkypeParcer.py
```

**Comment by ostrowsky** [comment]
Here is the listing:

C:\Users\user\Documents\Parser>python SkypeParcer.py
<= [18/05 11:28:21] GET https://login.skype.com/login/oauth/microsoft
{'params': {'client_id': '578134', 'redirect_uri': 'https://web.skype.com'}}
=> [18/05 11:28:22] 200
{'Cache-Control': 'max-age=0',
 'Connection': 'close',
 'Content-Encoding': 'gzip',
 'Content-Length': '8206',
 'Content-Type': 'text/html; charset=utf-8',
 'Date': 'Thu, 18 May 2017 08:28:12 GMT',
 'Expires': 'Thu, 18 May 2017 08:27:12 GMT',
 'P3P': 'CP="DSP CUR OTPi IND OTRi ONL FIN"',
 'Server': 'Microsoft-IIS/8.5',
 'Set-Cookie': 'uaid=aa6218b38c127bfaec65f89c6a156c36; '
               'domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1, '
               'MSPRequ=lt=1495096092&co=1&id=293290; secure= '
               ';path=/;HTTPOnly=;version=1, '
               'MSPOK=$uuid-dab3647c-ed8b-4ed5-87ab-ccb65deab2ab; '
               'domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1',
 'Strict-Transport-Security': 'max-age=31536000',
 'Vary': 'Accept-Encoding',
 'X-Content-Type-Options': 'nosniff',
 'X-Frame-Options': 'deny',
 'X-XSS-Protection': '1; mode=block'}
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 211, in __call__
    print(pformat(resp.json()))
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\requests\models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SkypeParcer.py", line 20, in <module>
    sk=Skype(user, password)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 264, in getSkypeToken
    self.liveLogin(user, pwd)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 361, in liveLogin
    self.tokens["skype"], self.tokenExpiry["skype"] = SkypeLiveAuthProvider(self).auth(user, pwd)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 534, in auth
    params = self.getParams()
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 541, in getParams
    params={"client_id": "578134", "redirect_uri": "https://web.skype.com"})
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 213, in __call__
    print(resp.text)
  File "C:\Users\user\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp866.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\xf4' in position 23230: character maps to <undefined>

**Comment by OllieTerrance** [comment]
Sigh, unicode.  😞  Maybe just run it interactively, catch the exception on reading `contact.chat`, and take a look at the response object yourself (it should be in `exc.args[1]` if you `except Exception as exc`; specifically, `exc.args[1].text`).

**Comment by ostrowsky** [comment]
I should run the script added with 
except Exception as exc: 
       print (exc.args[1])
 in interactive mode setting each contact manually and read the console log?

**Comment by OllieTerrance** [comment]
You have the failing contact ID, easiest thing to do is just run a Python shell and test it there:

```python
>>> from skpy import Skype
>>> sk = Skype(tokenFile=".tokens-ostrowsky_")
>>> try:
...     chat = sk.contacts["..."].chat  # NB. no 8: prefix
... except Exception as exc:
...     resp = exc.args[1]
... 
>>> # at this point either chat or resp should be set
```

**Comment by ostrowsky** [comment]
This code succeed:
from skpy import *

contacts = []
sk = Skype(user, password)
source_contacts = sk.contacts
for contact in source_contacts:
    contacts.append(str(contact.id))
print(contacts)
for contact in contacts:
    try:
        chat = sk.contacts[contact].chat
        if chat:
            print(chat, '\n')
    except Exception as exc:
        resp = exc.args[1]
        print(resp)

**Comment by OllieTerrance** [comment]
You mean it fails, but you've got `resp` to play with.  The whole point of this is to see what `resp.text` holds, if anything.  Based on the earlier exceptions, it's at least not JSON...

**Comment by ostrowsky** [comment]
No, i'v got this: {"errorCode":730,"message":"Failure due to: ConversationNotFound."}

**Comment by ostrowsky** [comment]
One of this messages is for contact "skynetservice": {"errorCode":730,"message":"Failure due to: ConversationNotFound."} You may try it. As far as I understand this is common contact for any skype account used for checking quality of calls.

**Comment by OllieTerrance** [comment]
The debugging stack trace from earlier (with `JSONDecodeError` and `UnicodeEncodeError`) is a red herring, unless you've cropped most of it -- the failing one there appears to be part of authentication.

---

The call-testing contact is called `echo123`:

```python
>>> sk.contacts["echo123"]
SkypeContact(id='echo123', name=Name(first='Echo / Sound Test', last='Service'),
             location=Location(), avatar='.../avatars/echo123/public',
             authorised=True, blocked=False, favourite=False)
```

And indeed I can't obtain a conversation for it, but I think that may be a special case -- you can't send messages to it in the official clients either.

I don't know what `skynetservice` is, but it's not a contact I have...

```python
>>> sk.contacts.contact("skynetservice") is None
True
```

**Comment by ostrowsky** [comment]
I've changed the script in order to exclude contacts that may cause error. Now there are no errors but I still get lists of messages only from few contacts instead of all of them. 
for contact in contacts:
    if contact not in ("evgen375291362177","skynetservice"):
        try:
            chat = sk.contacts[contact].chat
            if chat.getMsgs():
                print(chat.getMsgs())
        except Exception as exc:
            resp = exc.args
            print(resp)

**Comment by OllieTerrance** [comment]
That in itself doesn't tell me anything.  Do you get any messages, or none, or an exception?  You're calling it twice there; it'll return the second "page" of messages for the print, which could be empty by then...

**Comment by OllieTerrance** [comment]
This has been hanging around for a while with no further input, so I'll go ahead and close it.  If you've got a specific question or a reliably reproducible bug, feel free to discuss further.
