### ISSUE TITLE
Other API endpoint

### ISSUE THREAD

**Issue by dgikiller** [OllieTerrance/SkPy#63]
Hello, 

while googling around I found this project and I think it is really interesting. 
I noticed that there are, in 'other API' section, some interesting features like the Skype's services list. 
I just want to ask if this API will only list the specific service or it can be used to change the configuration of the service itself.
For example if I want to disable the call forwarding or change the number associated with it there is a specific endpoint that I can use?

Thank you very much for your time.

**Comment by OllieTerrance** [comment]
Not as far as I've seen -- Skype for Web doesn't provide any way to change service settings, that's all done inside the accounts site, so it's unlikely that APIs exist.  Of course, if you happen to find any in Skype for Web, I'd be happy to document them.  🙂

**Comment by dgikiller** [comment]
Indeed I saw that the only way to do this kind of things is to acquire somehow a verification token from the website. Maybe in future, if they will extend their APIs, we can do that even from Skype for Web.

**Comment by OllieTerrance** [comment]
Would be nice, but nothing we can do here unless Skype for Web gains the features first.
