### ISSUE TITLE
 It's possible to get old history of conversation?

### ISSUE THREAD

**Issue by dentakoy** [OllieTerrance/SkPy#64]
Hi everybody!

It's possible to get old history of conversation?
Method SkypeChat.getMsgs() return only recent messages.
I try to use SkypeChat.setConsumption() before getMsgs() with some different horizons: "0;0;0", "-1;-1;-1" and "1;1;1".
But i don't get positive results. :(

I use Skype account linked with Microsoft account.

**Comment by OllieTerrance** [comment]
Marking the conversation read is separate from fetching updates.  Messages are paginated, so you should just be able to call `getMsgs()` again for the next batch.  I'm not sure how far it goes back -- from limited previous testing it was less than the desktop clients, possibly 60-90 days -- but you'll have to keep iterating as there's no way to jump to a specific time or message.

See [Pagination](https://skpy.t.allofti.me/protocol/start.html#pagination) for how the Skype API provides paginated responses such as messages (you don't need to worry about the URLs it mentions, the method call does that for you).

**Comment by dentakoy** [comment]
Thank you, OllieTerrance! :)
