### ISSUE TITLE
skpy.core.SkypeAuthException: ("Couldn't retrieve t field from login response", <Response [200]>)

### ISSUE THREAD

**Issue by maiconbaumx** [OllieTerrance/SkPy#68]
Hello! I am getting the same problem that other guys here.. But, this account is only accessed from the same IP address, it has never been changed. Anyone can help?

`<= [22/08 00:24:09] POST https://login.live.com/ppsecure/post.srf
{'cookies': {'CkTst': '1503372249961',
             'MSPOK': '$uuid-3d75351c-92de-43b0-a1c3-1fd902086458',
             'MSPRequ': 'lt=1503372249&co=1&id=293290'},
 'data': {'PPFT': u'DYn2UphwKVclUKLXXNRmtR1pdh39uLy7!kooZLL24AOJGnFEKIua0IIhgOj53AOcYO7GUUl4qfhV0qKj8Tois2gErGmrVniH9!SzlaFodTdUFw1Lhgi0xh54XjAdCQT9!HJDJmrQuXPNVET*sn0mmFvZ6R*LkgSzrwC!rnbLOibSFlPqxbUCG*QlQ9jc1qD7ZNyUog!q0YLikGRMd8fi!EsDsVQvz2sFjG83Gv0J!4qrVuE4TTg5EXQ2nWZfFbhESQ$$',
          'login': 'xxx',
          'passwd': 'xxx'},
 'params': {'wa': 'wsignin1.0',
            'wp': 'MBI_SSL',
            'wreply': 'https://lw.skype.com/login/oauth/proxy?client_id=578134&site_name=lw.skype.com&redirect_uri=https%3A%2F%2Fweb.skype.com%2F'}}
=> [22/08 00:24:10] 200
{'cache-control': 'no-cache',
 'connection': 'close',
 'content-encoding': 'gzip',
 'content-length': '1054',
 'content-type': 'text/html; charset=utf-8',
 'date': 'Tue, 22 Aug 2017 03:24:09 GMT',
 'expires': 'Tue, 22 Aug 2017 03:23:10 GMT',
 'p3p': 'CP="DSP CUR OTPi IND OTRi ONL FIN"',
 'pragma': 'no-cache',
 'server': 'Microsoft-IIS/8.5',
 'set-cookie': 'uaid=8bcf407f2a9d14e15c13d51ed3b0c6f0; domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1, MSPOK= ; expires=Thu, 30-Oct-1980 16:00:00 GMT;domain=login.live.com;path=/;HTTPOnly= ;version=1, PPAuth=CSTL5VTDCj!EJzdloYtLQon5uz313g1XQODVjdHvl1bzo*XouUUWH8MJ9oiYKMP22vTVNA0SadS9l3wKMnCCbERe70tZdDCPx4vRaK5HHeqqDzofP6MSr6HqaikVz1Wst73zvpXaTvzpjZVDMZlQQGbB6YNym9CKF9EP!6tosHsGH0dKSFhpnfwycTOq73!Q248haD1EIwGd838cMgHmAjPLw2w1GFFZkvAsLEJ7WxVo9t4q!VWv1GsAqWMzOUdPVjSIgyAR2vDLAjoapsYQ1nTI64EL7PDsZ1L0cACLN!H0LKtm!ffAplG!7N5jl9dOQQ$$; domain=login.live.com;secure= ;path=/;HTTPOnly= ;version=1, PPLState=1; domain=.live.com;path=/;version=1, MSPShared= ; HTTPOnly= ; domain=login.live.com;path=/;Expires=Thu, 30-Oct-1980 16:00:00 GMT, MSPPre=xxxxx|1d0c2e28d602cc52||;domain=login.live.com;path=/;Expires=Wed, 30-Dec-2037 16:00:00 GMT;secure=, MSPCID=1d0c2e28d602cc52; HTTPOnly= ; domain=login.live.com;path=/;Expires=Wed, 30-Dec-2037 16:00:00 GMT;secure=, WLOpt=credtype=1&act=[1];domain=login.live.com;path=/;Expires=Wed, 30-Dec-2037 16:00:00 GMT;secure=, pres=; expires=Thu, 30-Oct-1980 16:00:00 GMT;domain=.live.com;path=/;version=1, LOpt=1; domain=login.live.com;path=/;version=1, MSPVis=$38936;domain=login.live.com;path=/, MSPBack=0; domain=login.live.com;path=/;version=1',
 'strict-transport-security': 'max-age=31536000',
 'vary': 'Accept-Encoding',
 'x-content-type-options': 'nosniff',
 'x-xss-protection': '1; mode=block'}
<html><head><noscript>JavaScript required to sign in<meta http-equiv="Refresh" content="0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033"/></noscript><title>Continue</title><script type="text/javascript">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload="javascript:DoSubmit();"><form name="fmHF" id="fmHF" action="https://account.live.com/profile/accrue?ru=https://login.live.com/login.srf%3flc%3d1033%26sf%3d1%26id%3d293290%26tw%3d18000%26fs%3d0%26ts%3d0%26sec%3d%26mspp_shared%3d1%26seclog%3d10%26claims%3d%26wa%3dwsignin1.0%26wp%3dMBI_SSL%26ru%3dhttps://lw.skype.com/login/oauth/proxy%253fclient_id%253d578134%2526site_name%253dlw.skype.com%2526redirect_uri%253dhttps%25253A%25252F%25252Fweb.skype.com%25252F%26contextid%3d68A21ED45E4DC9F4&mkt=EN-US&uiflavor=web&id=293290&uaid=8bcf407f2a9d14e15c13d51ed3b0c6f0&if=80000000&af=20" method="post" target="_top"><input type="hidden" name="ipt" id="ipt" value="DRdJrQ3uVEuAg9zTgApgbSncCug*BYp*jpfxd86cdcC1K0aLV3w0xxrqMFfS8wXcCKZvVmG7Pr!keLyuSIs2*YswiKO8GGcrmTQn0iqOmf4zfbwmVLc3iQgDrFjreF1Oi!Fmjxj3t1aH59l3WmyTFrquLE*tnZXclQC9cXHNJ*e1iV0jcEXckIhyc9ZvR1LFFcDzUxLe5KpBcbU9biWuCG4!XTAstaQHEBTZDZ2m!vRYknaFciOKJ9UKT5qwVZs4qL3trr9Dni0w4nE3techrYU2mecNbhI4p4yFvVkocgWlGAjVKU3ONRsKdqs9K*LivtOzuKl5yGUNRxTUFfxTLJFDbXGpLF3maruzT41EY*neSn6a!J0kqUdo5hmMJDSvHR5A88OADQDeAatRQ98PSjMAqjQdXWG6NN5BThV04GWGY2szTx4MSNwEgrlG5JDC25DAX27GllEInxX0UMbFjN1Zz74A1sIErdguqyQXoCwh"></form></body></html>
Traceback (most recent call last):
  File "slack-skype.py", line 60, in <module>
    sk = Skype(username, password, tokenFile=skypeToken)
  File "/usr/local/lib/python2.7/site-packages/skpy/main.py", line 69, in __init__
    self.conn.getSkypeToken()
  File "/usr/local/lib/python2.7/site-packages/skpy/conn.py", line 264, in getSkypeToken
    self.liveLogin(user, pwd)
  File "/usr/local/lib/python2.7/site-packages/skpy/conn.py", line 361, in liveLogin
    self.tokens["skype"], self.tokenExpiry["skype"] = SkypeLiveAuthProvider(self).auth(user, pwd)
  File "/usr/local/lib/python2.7/site-packages/skpy/conn.py", line 535, in auth
    t = self.sendCreds(user, pwd, params)
  File "/usr/local/lib/python2.7/site-packages/skpy/conn.py", line 568, in sendCreds
    raise SkypeAuthException(errMsg, loginResp)
skpy.core.SkypeAuthException: ("Couldn't retrieve t field from login response", <Response [200]>)
`

**Comment by OllieTerrance** [comment]
Please look at the existing issues, this has been raised multiple times already -- see #66, #65, #45.
