### ISSUE TITLE
Update PyPI

### ISSUE THREAD

**Issue by orenyomtov** [OllieTerrance/SkPy#69]
This common problem:
```
skpy.core.SkypeApiException: ('404 response from PUT https://db5-client-s.gateway.messenger.live.com/v1/users/ME/endpoints/<snip>/presenceDocs/messagingService', <Response [404]>)
```
Which several users have encountered, is not fixed in the PyPI version of SkPy.

Specifically, its `conn.py` file needs updating.
It is currently at this version:
https://github.com/OllieTerrance/SkPy/commit/741cffd2fe9abf1aec0c7db895dddc8d14346d38#diff-3f76e41bdeaab4f1f3989aa66219d780

But the fix was pushed in the following commit:
https://github.com/OllieTerrance/SkPy/commit/7b6be6e41238058b9ab644d908621456764fb6d6#diff-3f76e41bdeaab4f1f3989aa66219d780

**Comment by OllieTerrance** [comment]
Pushed 📦 v0.8.1 ([GitHub](https://github.com/OllieTerrance/SkPy/releases/tag/v0.8.1), [PyPI](https://pypi.python.org/pypi/SkPy/0.8.1)).

Apologies for the delay -- I was holding this pending some refactoring which I never got round to...

**Comment by orenyomtov** [comment]
Thanks for the blazingly fast turnaround - the PyPI package is now working perfectly
