### ISSUE TITLE
Login success,but get contacts nothing

### ISSUE THREAD

**Issue by adou28** [OllieTerrance/SkPy#71]
When I copy the demo code from usage docs and run it.
`from skpy import Skype
sk = Skype('xxx', 'xxx') # connect to Skype

sk.user # you
sk.contacts # your contacts
sk.chats # your conversations`

I found that I can't get any info about contacts.It's empty.Seems like sync failed.
How can I deal with it?Thx

**Comment by OllieTerrance** [comment]
How do you know it's empty?  The repr will just show `SkypeContacts()` regardless of how many you have -- you need to either [fetch one by ID](https://skpy.t.allofti.me/usage.html#retrieving-contacts), or loop over `sk.contacts` to work with all of them (the API request is made on first access).

**Comment by adou28** [comment]
I thing I have figured out the problem.I have to two different accounts.One is pure SkypeId that was registered long years before.The other is MicrosftID.When I loggin the SkypeID account, I can't get anything for the sk.contacts.contactIds.And then when I call  sk.contacts.sync(),catch nonetype exception but at this time,u can find that sk.contacts.contactIds has been synced. As same opreation in MicrosoftID, the different is none of exception I catch. In short, no matter what kind of account I choose,first of all I have to call sync() function so that sk.contacts would be synced.Otherwise I can't fetch one by ID cause  sk.contacts.contactIds is empty.

**Comment by OllieTerrance** [comment]
`SkypeContacts.contactIds` is an implementation detail, don't use that.  [The docs](https://skpy.t.allofti.me/api.html#skpy.user.SkypeContacts) state the available methods and idioms you can use with contacts -- as explained above, you should either do a key lookup or loop over it, both of which call `sync()` on first access.

**Comment by adou28** [comment]
Thx a lot,It's very nice that u can reply my question in time.I'm done.
