### ISSUE TITLE
407 Error when Windows is connected to a Proxy

### ISSUE THREAD

**Issue by DarkSyken** [OllieTerrance/SkPy#74]
Hello! I've been trying a few solutions to this, but I cannot find exactly how to handle it. My PC connects through a proxy to monitor web activity and apply proper filtering. Unfortunately, as soon as the proxy is activated i get the following error:
407 Proxy Authentication Required

Without the proxy, everything works perfectly fine. Unfortunately, I cannot turn off the proxy as a solution.

Any help would be greatly appreciated!

### Steps to reproduce

Steps:
1. Enable a Proxy on a Windows PC.
2. Run the following:
```
from skpy import Skype
username = "username"
password = "password"
tokenfile = "tokenfile"

sk = Skype(username, password, tokenfile)
```

### Here are the results I get:
(Address on my PC has been replaced by [Address] and token file name has been censored too)
### 1.
Traceback (most recent call last):
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\urllib3\connectionpool.py", line 595, in urlopen
    self._prepare_proxy(conn)
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\urllib3\connectionpool.py", line 816, in _prepare_proxy
    conn.connect()
  File "[Address]\Local\Programs\Python\Python35-32\lib\site-packages\urllib3\connection.py", line 294, in connect
    self._tunnel()
  File "[Address]\Programs\Python\Python35-32\lib\http\client.py", line 809, in _tunnel
    message.strip()))
OSError: Tunnel connection failed: 407 Proxy Authentication Required

### 2.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='flagsapi.skype.com', port=443): Max retries exceeded with url: /flags/v1 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))

### 3.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[Address]", line 12, in <module>
    tokenFile="tokenfilename")
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\skpy\main.py", line 72, in __init__
    self.settings = SkypeSettings(self)
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\skpy\main.py", line 291, in __init__
    self.syncFlags()
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\skpy\main.py", line 323, in syncFlags
    auth=SkypeConnection.Auth.SkypeToken).json())
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\skpy\conn.py", line 206, in __call__
    resp = self.sess.request(method, url, headers=headers, **kwargs)
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "[Address]\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='flagsapi.skype.com', port=443): Max retries exceeded with url: /flags/v1 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',))

**Comment by OllieTerrance** [comment]
SkPy uses the Requests library for HTTP requests, which supports the use of `HTTP_PROXY` and `HTTPS_PROXY` environment variables.  Does setting them [as described here](http://docs.python-requests.org/en/latest/user/advanced/#proxies) allow you to authenticate with your proxy?

**Comment by DarkSyken** [comment]
Hey Ollie! Thanks for the answer, I've been trying to setup those using a few dozens of ways, the tunnel always fail regardless of how I set it up. The core of the error being:
OSError: Tunnel connection failed: 407 Proxy Authentication Required
I've been setting up os.environ ["HTTP_PROXY"], ["HTTPS_PROXY"] to the address "http://user:password@host:port" (with proper username, password, proxy server and port). 

When I put in the following code, the error occurs (censored some stuff):
```
from skpy import Skype
import re
import openpyxl
import os
import getpass
import requests

proxy = r'http://user:pwd@proxy.domain.local:port'

os.environ['http_proxy'] = proxy 
os.environ['HTTP_PROXY'] = proxy
os.environ['https_proxy'] = proxy
os.environ['HTTPS_PROXY'] = proxy

#SkypeVariable#
username = "username"
password = "password"

sk = Skype(username, password, \
tokenFile="nameoftokenfile")
```

and got this error at the bottom:
```
  File "[path]\Programs\Python\Python35-32\lib\site-packages\requests\adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.live.com', port=443): Max retries exceeded with url: /login.srf?wa=wsignin1.0&rpsnv=13&ct=1515536444&rver=6.7.6626.0&wp=MBI_SSL&wreply=https%3A%2F%2Flw.skype.com%2Flogin%2Foauth%2Fproxy%3Fclient_id%3D578134%26redirect_uri%3Dhttps%253A%252F%252Fweb.skype.com%26site_name%3Dlw.skype.com&lc=1033&id=293290&mkt=en-CA&uaid=dd753c0f5944da8b9beb13c04d0159ab&psi=skype&lw=1&cobrandid=90010&client_flight=hsu%2CReservedFlight33%2CReservedFlight67 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required',)))
```
We did whitelist a few addresses through the proxy before I reached that point, which may be the only reason I get this far. (https://web.skype.com, login.skype.com, co4-client-s.gateway.messenger.live.com, flagsapi.skype.com)

**Comment by OllieTerrance** [comment]
You could whitelist, though there are quite a few domains involved:

https://github.com/OllieTerrance/SkPy/blob/master/skpy/conn.py#L127-L143

Are you able to make a connection via your proxy by using requests directly?

```python
requests.get("https://httpbin.org/get")
```

Only other thing I can think of is it might be too late to use `os.environ` -- any change if you actually set them in your environment rather than patching them in on the Python side?

**Comment by OllieTerrance** [comment]
You could whitelist, though there are quite a few domains involved:

https://github.com/OllieTerrance/SkPy/blob/6c97c6a8dab71bc9aec7f20cbe8aff95d23c384e/skpy/conn.py#L127-L143

Are you able to make a connection via your proxy by using requests directly?

```python
requests.get("https://httpbin.org/get")
```

Only other thing I can think of is it might be too late to use `os.environ` -- any change if you actually set them in your environment rather than patching them in on the Python side?

**Comment by DarkSyken** [comment]
Hey Ollie! Sorry for the slow reply, that was a big week! So, with our IT department, we've tried lots of stuff, none of those worked until we added exclusion to localhost (or exception to localhost?). Basically, we really had to setup the proxy to let those communication pass through.
Thanks a lot for the support!
