### ISSUE TITLE
How to listen to all incoming messages?

### ISSUE THREAD

**Issue by sumit6192** [OllieTerrance/SkPy#75]

**Comment by sumit6192** [comment]
Hi ,
How can i listen() to all incoming messages along with the user name or id.

i found the following function:
from skpy import SkypeEventLoop, SkypeNewMessageEvent
class SkypePing(SkypeEventLoop):
    def __init__(self):
        super(SkypePing, self).__init__(username, password)
    def onEvent(self, event):
        if isinstance(event, SkypeNewMessageEvent) \
          and not event.msg.userId == self.userId \
          and "ping" in event.msg.content:
            event.msg.chat.sendMsg("Pong!")
but couldnt make it work could you please give a basic example to show how i can listen to all incoming messages cos i find this module to be extremely kool and easy to use..
Kindly help me with this

**Comment by OllieTerrance** [comment]
> please give a basic example

You're looking at the example, you quoted* it there.

> couldnt make it work

Why not?  Are you running that code as-is?  What output are you getting?

---

\* P.S. https://help.github.com/articles/creating-and-highlighting-code-blocks/
