### ISSUE TITLE
how to listen latest incoming message in scheduler? 

### ISSUE THREAD

**Issue by hardiksanchawat** [OllieTerrance/SkPy#76]
### Account type

Microsoft Account

### Conversation details

1 to 1

### Steps to reproduce

I have created one script for send and receive message. But I want to receive only latest message, Instead of that receiving older message and latest message as well. 

```
from skpy import Skype
import regex as re
import time
import os
import sched, time

sk=Skype('skype mail id','passwd')

ch = sk.contacts['another user id'].chat
ch.sendMsg('cab is booked')

s = sched.scheduler(time.time, time.sleep)
def id_msg(sc):
    xx=str(ch.getMsgs()[0])

    content=re.split('Content',xx)[-1]
    chatid=re.split('ChatId',xx)[-1]
    tm=re.split('Time',xx)[-1]

    tim = tm.lstrip(': ').split('\n')[0]
    ids=chatid.lstrip(': 8:').split('\n')[0]
    message=content.replace(':','').strip()
    print (ids,message,tim)
    s.enter(30, 1, id_msg, (sc,))
s.enter(30, 1, id_msg, (s,))
s.run()
```

### Output
**[latest received msg]**
```
('another user id', 'thanks', '2018-01-13 10:34:27.114000')
```
**[older received msg]**
```
('another user id', 'xyz', '2018-01-13 08:32:53.139000')
('another user id', 'mno', '2018-01-12 10:49:54.269000')
```

@OllieTerrance Is there any function to receive only latest message ?
Thanks in Advance!

**Comment by OllieTerrance** [comment]
[`getMsgs()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChat.getMsgs) will retrieve a fixed number of messages each time it's called, which may be old or new (if any new messages have arrived since the last call).  If you just want to receive new messages, you need an [event loop](https://skpy.t.allofti.me/usage.html#event-processing) to listen for them.

**Comment by hardiksanchawat** [comment]
@OllieTerrance I saw and try to understand [event loop](https://skpy.t.allofti.me/usage.html#event-processing). But how would I receive latest message? Could you please give me example to get latest incoming message. 
Thanks for guiding me!

**Comment by OllieTerrance** [comment]
There's an example in the [readme](https://github.com/OllieTerrance/SkPy#event-processing) and an initial explanation on that doc page, but effectively you need to:

* subclass [`SkypeEventLoop`](https://skpy.t.allofti.me/api.html#skpy.main.SkypeEventLoop) to implement [`onEvent()`](https://skpy.t.allofti.me/api.html#skpy.main.SkypeEventLoop.onEvent)
* check the event is an instance of [`SkypeMessageEvent`](https://skpy.t.allofti.me/api.html#skpy.event.SkypeMessageEvent) (or a subclass depending on your needs)
* do something with `event.msg`

**Comment by hardiksanchawat** [comment]
```
from skpy import SkypeEventLoop, SkypeNewMessageEvent
class SkypePing(SkypeEventLoop):
    def __init__(self):
        super(SkypePing, self).__init__(username, password)
    def onEvent(self, event):
        if isinstance(event, SkypeNewMessageEvent) \
          and not event.msg.userId == self.userId \
          and "ping" in event.msg.content:
            event.msg.chat.sendMsg("Pong!")
            event.msg.chat.SkypeMsg()
```

I have tried above code but it's gives me traceback.

For event.msg.content (if condition)
AttributeError: 'SkypePresenceEvent' object has no attribute 'msg'

isinstance(event, SkypeNewMessageEvent) (if condition)
False

Due to this if condition not execute. Please let me know if I did any mistake @OllieTerrance

**Comment by OllieTerrance** [comment]
So you received a [`SkypePresenceEvent`](https://skpy.t.allofti.me/api.html#skpy.event.SkypePresenceEvent) from Skype.

> isinstance(event, SkypeNewMessageEvent) (if condition)
> False

As expected.

> AttributeError: 'SkypePresenceEvent' object has no attribute 'msg'

If you're checking it's a `SkypeNewMessageEvent` first, how are you getting attribute errors from reading `event.msg`?  Are you using the exact code you posted above?  As it is, the first if condition should short-circuit and skip the subsequent checks.

> ```event.msg.chat.SkypeMsg()```

That's definitely not going to work, don't do that.

**Comment by hardiksanchawat** [comment]
My code is:
```
from skpy import SkypeEventLoop, SkypeNewMessageEvent
class SkypeMsg(SkypeEventLoop):
    def __init__(self):
        super(SkypeMsg, self).__init__(username, password)
    def onEvent(self, event):
        print (isinstance(event,SkypeNewMessageEvent))
        print (event.msg.userId)
        print (event.msg.content)
        if isinstance(event,SkypeNewMessageEvent) and not event.msg.userId == self.userId and "ping" in event.msg.content:
            event.msg.chat.sendMsg("Pong!")
sm = SkypeMsg()
sm.loop()
```


Traceback:
```
<ipython-input-7-cc1687bd93d3> in onEvent(self, event)
      5     def onEvent(self, event):
      6         print (isinstance(event,SkypeNewMessageEvent))
----> 7         print (event.msg.userId)
      8         print (event.msg.content)
      9         if isinstance(event,SkypeNewMessageEvent) and not event.msg.userId == self.userId and "ping" in event.msg.content:

AttributeError: 'SkypePresenceEvent' object has no attribute 'msg'
```
@OllieTerrance  I am using same code I've posted above. In Traceback Line no 6 gave me result  ``` False ``` and Line 7-8 gave me same traceback  ``` AttributeError: 'SkypePresenceEvent' object has no attribute 'msg' ```

I don't understand why SkypePresenceEvent object is coming. I didn't use this class anywhere in my code. :(

**Comment by OllieTerrance** [comment]
You've confirmed it's not a `SkypeNewMessageEvent` but then you're trying to read `event.msg` anyway in the print statement.  Remove those (or put them inside the if block) and it should work.

> I don't understand why SkypePresenceEvent object is coming.

Because Skype will send you any events that occur, not just the ones you're interested in, hence the need to filter using `isinstance()`.  You may find it easier to structure your code like this, particularly if you do later decide to handle different types of events:

```python
def onEvent(self, event):
    if isinstance(event, SkypeNewMessageEvent):
        self.onMessage(event)
    # For further types:
    # elif isinstance(event, ...): ...

def onMessage(self, event):
    print(event.msg.userId)
    print(event.msg.content)
    # etc.
```

> ```class SkypeMsg(SkypeEventLoop):```

I'd recommend you pick a different name, [`SkypeMsg`](https://skpy.t.allofti.me/api.html#skpy.msg.SkypeMsg) is already defined.

**Comment by hardiksanchawat** [comment]
Finally its working for me. :) Thanks @OllieTerrance 👍
