### ISSUE TITLE
Help avoiding Auth Rate Limit Exceeded

### ISSUE THREAD

**Issue by ldmldmldm** [OllieTerrance/SkPy#80]
### Issue

I am logging in once per day and retrieving contacts, conversations, and messages from conversations. But I get the dreaded `Auth rate limit exceeded`.

I use tokenFile when logging in however I suspect this is not helping me much as I login once per day. My script is usually able to log in but while it is performing it's activities the rate limit triggers, so I suspect it's due to the number of calls I make.

When I go to the web interface no captcha is presented and I am able to click on all conversations and scroll upwards and view all messages. So I'm not really sure what Skpy is going differently.

Is there any way to avoid the `Auth rate limit exceeded`? Do you know if editing my local version of Skpy to insert a `time.sleep(0.1)` between each call would help? Any other ideas?

### Account type

Using a couple of Live (Microsoft) accounts.

### Conversation details

All types of conversations.

### Steps to reproduce

1. Login
2. Retrieve contacts
3. Retrieve conversations
4. Call getMsgs on each conversation

### Result or traceback

Result: `Auth rate limit exceeded`
Traceback: TBD

**Comment by OllieTerrance** [comment]
You're getting `Auth rate limit exceeded` as a direct result of calling `getMsgs()` on a conversation?  I was of the impression that the error code for that was specific to logging in.  Please include some sample code showing how you're logging in and retrieving messages.

No rate limiting here from requesting messages of all an account's known conversations (x169) in a loop.

**Comment by ldmldmldm** [comment]
I am able to log in. I then get contacts. I then get `recent()` chats in a loop until all have been retrieved. I then `getMsgs()` on each chat in a loop until all has been retrieved. Sometime during the `recent()` calls or the `getMsgs()` calls I receive the `Auth rate limit exceeded`. It would look like this:

```python
from skpy import Skype
session = Skype("username", "password", "tokenFile")

for contact in session.contacts:
    print(contact)

while session.chats.recent()
    print('populating chats')
    continue

for chat in session.chats.cache:
    print('populating messages')
    msgs = []
    while true:
        print(f'getting messages for chat {chat}')
        new = chat.getMsgs()
        msgs += new
        if not new:
            break
    print(msgs)
```

I guess I'll need to get you the debug log transcript, maybe somethings getting blocked in the firewall leading to each request being a new auth or something?

**Comment by ldmldmldm** [comment]
I tested the sample code I provided in my previous comment and had no issue, so I found the difference with my real code which turned out to be a lookup for people in the Skype directory. It was indeed this lookup to the Skype directory `https://skypegraph.skype.com` that was resulting in the `Auth rate limit exceeded` error.
