### ISSUE TITLE
Problem getting messages from conversation with bot

### ISSUE THREAD

**Issue by VyacheslavStepanov** [OllieTerrance/SkPy#81]
I'm trying to get chat mesages but it raises an exception with a 404 http code:

`>>>chat = sk.chats["29:1Pkqbwc0IjKJF65UWNc57w61Tm5j3-OhwNg9fn213c8Y"]

Traceback (most recent call last):
    File "C:\Users\sweb\fmon2\mon\venv\lib\site-packages\skpy\chat.py", line 391, in __getitem__
    return super(SkypeChats, self).__getitem__(key)
    File "C:\Users\sweb\fmon2\mon\venv\lib\site-packages\skpy\core.py", line 138, in __getitem__
    return self.cache[key]
KeyError: '29:1Pkqbwc0IjKJF65UWNc57w61Tm5j3-OhwNg9fn213c8Y'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\sweb\fmon2\mon\venv\lib\site-packages\skpy\chat.py", line 393, in __getitem__
    return self.chat(key)
  File "C:\Users\sweb\fmon2\mon\venv\lib\site-packages\skpy\chat.py", line 429, in chat
    auth=SkypeConnection.Auth.RegToken, params={"view": "msnp24Equivalent"}).json()
  File "C:\Users\sweb\fmon2\mon\venv\lib\site-packages\skpy\conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('404 response from GET https://ch1-client-s.gateway.messenger.live.com/v1/users/ME/conversations/29:1Pkqbwc0IjKJF65UWNc57w61Tm5j3-OhwNg9fn213c8Y', <Response [404]>)`

**Comment by demurgos** [comment]
@VyacheslavStepanov 
To clarify, `29:1Pkqbwc0IjKJF65UWNc57w61Tm5j3-OhwNg9fn213c8Y` is what Skype calls an MRI key. It's an id prefixed by code indicating the type of the resource. We never saw the MRI type code `29`: what kind of resource is this? Is this a special kind of contact or chat group?


For reference, here are the types I am aware of:

```
const MRI_TYPE_TO_TYPE_CODE: Map<MriType, MriTypeCode> = new Map<MriType, MriTypeCode>([
  [MriType.Agent, "28"],
  [MriType.Lync, "2"],
  [MriType.Msn, "1"],
  [MriType.Skype, "8"],
  [MriType.Pstn, "4"],
  [MriType.GroupConversation, "19"],
]);
```

**Comment by VyacheslavStepanov** [comment]
It is id of conversation with a Microsoft Teams bot. https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#full-inbound-schema-example

**Comment by VyacheslavStepanov** [comment]
I got activity json from bot and saw in recipient field prefix 28. This was id of needed bot.
{"Activity":{"type":"message","id":"1523363704294","timestamp":"2018-04-10T12:35:04.295Z","localTimestamp":null,"serviceUrl":"https://smba.trafficmanager.net/apis/","channelId":"skype","from":{"id":"29:1Pkqbwc0IjKJF65UWNc57w61Tm5j3-OhwNg9fn213c8Y","name":null},"conversation":{"isGroup":null,"id":"29:1Pkqbwc0IjKJF65UWNc57w61Tm5j3-OhwNg9fn213c8Y","name":null},"recipient":{"id":"28:269373c8-529e-418e-b6a9-ec084f38265c","name":"smon_monq_bot"},"textFormat":null,"attachmentLayout":null,"membersAdded":[],"membersRemoved":[],"reactionsAdded":null,"reactionsRemoved":null,"topicName":null,"historyDisclosed":null,"locale":null,"text":"service::echo-json","speak":null,"inputHint":null,"summary":null,"suggestedActions":null,"attachments":[],"entities":[{"type":"clientInfo","locale":"ru-RU","country":"RU","platform":"Windows"}],"channelData":{"text":"service::echo-json"},"action":null,"replyToId":null,"value":null,"name":null,"relatesTo":null,"code":null},"Text":null,"UserId":0}
Using this id got messages - "ms = sk.chats["28:269373c8-529e-418e-b6a9-ec084f38265c"].getMsgs()"
I did't fully understand wats goin on but I solved my problem. Thank u very much for all comments!

**Comment by OllieTerrance** [comment]
MS Teams uses Skype for Business under the hood -- whilst there is interop between consumer Skype and S4B, I'm not sure where SkPy comes in to testing a bot through Teams?  I'm guessing this is through Bot Framework, but I would expect conversations on different protocols to use different identifiers etc. and generally not interact with each other.
