### ISSUE TITLE
Can't send files

### ISSUE THREAD

**Issue by farodrig** [OllieTerrance/SkPy#82]
I can't send files through chat.sendFile. When I do it I receive:

"skpy.core.SkypeApiException: ('400 response from POST https://api.asm.skype.com/v1/objects', <Response [400]>)"

I haven't changed my code and 3 months ago It worked perfectly.

I'm using a Microsoft account, I can login to https://web.skype.com with that account and don't have any problem.

In a 1-to-1 conversation. I can send files through other clients. I can't send any kind of file (image, audio, video, etc)

I hope anyone can help me.

**Comment by OllieTerrance** [comment]
You missed the important part of the issue template:

> ### Result or traceback
> 
> Please set `SKPY_DEBUG_HTTP=1` in your environment to capture API requests to Skype's servers.  Include the relevant parts (not the entire output), \```enclosed in backticks``` for readability.  Make sure to **remove any personal information** such as passwords or tokens before posting.

**Comment by punapun1** [comment]
Hi, I also face this same issue, had no problems before this. Sorry I'm a newbie to github and debugging, do let me know what more information is needed.

**Comment by punapun1** [comment]
Here's the error, receiving `NameError: global name 'pformat' is not defined` when setting `SKPY_DEBUG_HTTP=1`. This is the error without it.

`Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\skpy\chat.py", line 163, in sendFile
    auth=SkypeConnection.Auth.Authorize, json=meta).json()["id"]
  File "C:\ProgramData\Anaconda2\lib\site-packages\skpy\conn.py", line 217, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('400 response from POST https://api.asm.skype.com/v1/objects', <Response [400]>)
[Finished in 7.5s with exit code 1]
`

**Comment by OllieTerrance** [comment]
> receiving `NameError: global name 'pformat' is not defined` when setting `SKPY_DEBUG_HTTP=1`

Did you set it manually via `os.environ`?  It'll only import from `pprint` if set at startup.  (Arguably a bug in itself, but the debug logging is a mess and really needs redoing using `logger`.)

**Comment by punapun1** [comment]
=> [11/04 03:13:25] 400
{'Content-Length': '45',
 'Content-Type': 'application/json; charset=utf-8',
 'Date': 'Tue, 10 Apr 2018 20:13:25 GMT',
 'Server': 'Microsoft-IIS/8.5',
 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
 'X-Powered-By': 'ARR/2.5, ASP.NET'}
{u'message': u'PlatformId need to be specified'}

Is this what you needed? Thanks for your help

**Comment by OllieTerrance** [comment]
New header required on POST https://api.asm.skype.com/v1/objects: `X-Client-Version`

It appears to take the form `id/version`, where `version` is that of the web client, and `id` is obtained in a cookie called `platformid_asm` from POST https://api.asm.skype.com/v1/skypetokenauth.

I'll hopefully push a fix later today; in the meantime, the following patch appears to work:

```diff
diff --git a/skpy/chat.py b/skpy/chat.py
index bc3ad45..1e71bbb 100644
--- a/skpy/chat.py
+++ b/skpy/chat.py
@@ -161,5 +161,7 @@ class SkypeChat(SkypeObj):
             meta["filename"] = name
         objId = self.skype.conn("POST", "https://api.asm.skype.com/v1/objects",
-                                auth=SkypeConnection.Auth.Authorize, json=meta).json()["id"]
+                                auth=SkypeConnection.Auth.Authorize,
+                                headers={"X-Client-Version": "0/0.0.0.0"},
+                                json=meta).json()["id"]
         objType = "imgpsh" if image else "original"
         urlFull = "https://api.asm.skype.com/v1/objects/{0}".format(objId)
```
