### ISSUE TITLE
*.directory.live.com API endpoints retired

### ISSUE THREAD

**Issue by Jerning** [OllieTerrance/SkPy#84]
hi Terrance!
I can't ues your skpy
Some time ago is good

SkypeApiException: ('400 response from GET https://pf.directory.live.com/profile/mine/System.ShortCircuitProfile.json', <Response [400]>)

**Comment by Jerning** [comment]
i want to chat my group
because i applied in the group robot


Jerning Chan


在 2018年5月16日 星期三，02:39，Terrance 写道：

**Comment by Jerning** [comment]
HI, Terrance!
    how can i find out the group in my account?
the Skype.contacts.sync() rely Skype.profile  


Jerning Chan


在 2018年5月16日 星期三，02:39，Terrance 写道：

**Comment by OllieTerrance** [comment]
> the Skype.contacts.sync() rely Skype.profile

No it doesn't...

You don't need to call `sync()` anyway, either request a specific contact ID if you know it, or iterate over `Skype.contacts` to work with all contacts.

```python
>>> sk = Skype(...)
>>> sk.contacts["fred.2"]
SkypeContact(id='fred.2', name=Name(first='Fred', last='Adams'),
             location=Location(), language='EN', avatar='https://avatar.skype.com/...',
             phones=[], authorised=True, blocked=False, favourite=True)
>>> for c in sk.contacts:
...     print(c.id)
...
fred.2
joe.4
anna.7
```

**Comment by OllieTerrance** [comment]
Latest commit removes `Skype.profile`, so if you are trying to read it, you'll get an `AttributeError` instead.

**Comment by Jerning** [comment]
ok，Thank you so mush !

Jerning Chan


在 2018年5月16日 星期三，20:03，Terrance 写道：

**Comment by Jerning** [comment]
Hi, Terrance!
    After the last update of skype, your skpy library can't log in. May I ask this question, can I take the time to help repair it?


Jerning Chan


在 2018年5月16日 星期三，10:42，Jerning Chan 写道：
