### ISSUE TITLE
Trouble

### ISSUE THREAD

**Issue by neiks** [OllieTerrance/SkPy#85]
Traceback (most recent call last):
  File "./skpy", line 269, in <module>
    print(sk.contacts[user]);
  File "/usr/local/lib/python2.7/dist-packages/skpy/user.py", line 350, in __getitem__
    return self.skype.user if key == self.skype.userId else self.user(key)
  File "/usr/local/lib/python2.7/dist-packages/skpy/user.py", line 421, in user
    auth=SkypeConnection.Auth.SkypeToken, data={"contacts[]": id}).json()
  File "/usr/local/lib/python2.7/dist-packages/skpy/conn.py", line 219, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('404 response from POST https://api.skype.com/users/self/contacts/profiles', <Response [404]>)

**Comment by OllieTerrance** [comment]
Please re-read the issue template and include all the requested details.

> ### Steps to reproduce
> Explain how to (reliably) recreate the issue.  A short code sample may be useful.
> If applicable, test the corresponding action on https://web.skype.com to see if it works there.
> ### Result or traceback
> Please set `SKPY_DEBUG_HTTP=1` in your environment to capture API requests to Skype's servers.
> Include the relevant parts (not the entire output), ```enclosed in backticks``` for readability.
> Make sure to *remove any personal information* such as passwords or tokens before posting.

**Comment by neiks** [comment]
I'm afraid that my debug will not help, it generally ceased to work a few days ago. Before that there was a half year

**Comment by OllieTerrance** [comment]
If it stopped working without you changing your code, it's likely a change to the APIs themselves, hence my request for API output -- there's often a semi-useful response that hints at what's changed.

In lieu of a code sample to work with, I eventually reproduced it locally -- looks like the only use of that endpoint is to retrieve non-contact users.

As it stands, I can't actually see a way to do this from Skype for Web, their directory search has been broken for a while.  Pinging a non-contact from another client causes the conversation to appear on web, but the contact is mysteriously retrieved from a delta call without specifying the contact ID:

    https://contacts.skype.com/contacts/v2/users/$me?delta&reason=notification

**Comment by OllieTerrance** [comment]
Looks like `https://profile.skype.com/profile/v1/batch/profiles` works as a drop-in replacement.
