### ISSUE TITLE
Usage of setConsumption()

### ISSUE THREAD

**Issue by dharshanv07** [OllieTerrance/SkPy#86]
In one-to-one conversation how to set read / setconsumption? What should be the value of horizon?  can anyone provide an example

**Comment by OllieTerrance** [comment]
It might help to know why you want to do this.  [`SkypeChat.setConsumption()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChat.setConsumption) exists more as an implementation detail -- the only real use of it is to mark all messages as read, which [`SkypeMsg.read()`](https://skpy.t.allofti.me/api.html#skpy.msg.SkypeMsg.read) does for you:

https://github.com/OllieTerrance/SkPy/blob/03042f1732dd103ba252af9e27e2bf76b62a3b4e/skpy/msg.py#L262-L266

**Comment by dharshanv07** [comment]
I want to mark the messages from a particular user as read till a time t, since when i'm having a one to one conversation the read messages are trigged as newmessage event when i use getEvents().

**Comment by OllieTerrance** [comment]
Calling `SkypeMsg.read()` will emit a [`SkypeChatUpdateEvent`](https://skpy.t.allofti.me/api.html#skpy.event.SkypeChatUpdateEvent), which you should then ignore -- you've already consumed up to the horizon it specifies as you were the one to set it; the event exists to allow other clients to update their local state.

**Comment by dharshanv07** [comment]
What value should i pass to the horizon argument. can you give an example for this <id>,<timestamp>,<id> .

**Comment by OllieTerrance** [comment]
I already did, see `SkypeMsg.read()` above.  It's also stated in the docs:

> **horizon** (_str_) -- new horizon string, of the form `<id>,<timestamp>,<id>`

**Comment by dharshanv07** [comment]
<id> and <timestamp> values

**Comment by OllieTerrance** [comment]
Once again, from the sample above:

* a message ID, such as [`SkypeMsg.clientId`](https://skpy.t.allofti.me/api.html#skpy.msg.SkypeMsg.clientId)
* a UNIX timestamp, such as `time.time()` for the current time, in milliseconds

**Comment by dharshanv07** [comment]
Sorry,still i'm getting the same error.



ch.setConsumption(horizon=(z[0].clientId,time.time(),z[0].clientId))
  File skpy/chat.py", line 207, in setConsumption
    json={"consumptionhorizon": horizon})
  File "/skpy/conn.py", line 219, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('400 response from PUT https://hk2-2-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:live:abcd/properties', <Response [400]>)

**Comment by OllieTerrance** [comment]
You're sending a tuple, not a string.  The response will probably hint at invalid parameters if you look at it.

**Comment by dharshanv07** [comment]
I checked type of horizon it returning a str / string.

**Comment by OllieTerrance** [comment]
> horizon=(z[0].clientId,time.time(),z[0].clientId)

That is most definitely a tuple of three items, not a string, so I don't know where you attempted to check it.

---

It appears you're not very familiar with Python. I would suggest brushing up on the basics before trying to use a library like this one, it's not a particularly good resource for newcomers.  [Learn Python the Hard Way](https://learnpythonthehardway.org/python3/) may be a good place to start.

Questions or bugs specific to the library are of course welcome here, but you're expected to bring a basic understanding of the language you're attempting to use.  Until then, there are better places to ask for general Python support.

**Comment by OllieTerrance** [comment]
I can't tell you much more unless you actually post your code and the API output as requested in the issue template.

> ### Steps to reproduce
> Explain how to (reliably) recreate the issue.  A short code sample may be useful.
> If applicable, test the corresponding action on https://web.skype.com to see if it works there.
> ### Result or traceback
> Please set `SKPY_DEBUG_HTTP=1` in your environment to capture API requests to Skype's servers.
> Include the relevant parts (not the entire output), \```enclosed in backticks``` for readability.
> Make sure to *remove any personal information* such as passwords or tokens before posting.
