### ISSUE TITLE
404 Error Code 703 ConversationNotFound

### ISSUE THREAD

**Issue by pornstache321** [OllieTerrance/SkPy#87]
### Account type

Skype

### Conversation details

Issue is with 1-to-1 chats

### Steps to reproduce

Simply can't access SkypeSingleChat for all contacts.  

`s = Skype(username, getpass())`
`chat = s.contacts['some.user'].chat`

### Result or traceback

  File "C:\Users\user\AppData\Local\Programs\Python\Python35\lib\site-packages\skpy\conn.py", line 219, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
skpy.core.SkypeApiException: ('404 response from GET https://hk2-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:some.user', <Response [404]>)

Response JSON from Skype server is:

```{"errorCode":730,"message":"Failure due to: ConversationNotFound."}```

I think this is because there is no 1-to-1 chat already open for this contact.  I have searched the docs and not found a way to open a 1-to-1 chat, only how to start group chat.  Anything I'm missing?

**Comment by OllieTerrance** [comment]
Curious, looks like I have one contact that does this.  It's someone I haven't spoken to in a while (possibly never) so message history anyway.  Skype for Web doesn't seem to retrieve info about the conversation any more, but does see a 404 trying to get the message history, which it ignores.

As a workaround, manually setting a property seems to auto-create the conversation:

```python
>>> sk.contacts["joe.4"].chat
skpy.core.SkypeApiException: ('404 .../users/ME/conversations/8:joe.4', <Response [404]>)
>>> chat = skpy.SkypeSingleChat(skype=sk, id="8:joe.4", userId="joe.4", alerts=True)
# No server API calls made, just a local object.
>>> chat
SkypeSingleChat(id="8:joe.4", alerts=True, userId="joe.4")
# Set a property on the chat.
# PUT .../users/ME/conversations/8:joe.4/properties
>>> chat.setAlerts(True)
# Now the conversation exists on the server.
>>> sk.contacts["joe.4"].chat
SkypeSingleChat(id="8:joe.4", alerts=True, userId="joe.4")
```

I suspect sending a message to it would also auto-create it if they're already a contact, but I haven't got another one to play with.

In any case, looks like we can't rely on the conversation existing by default any more.

**Comment by pornstache321** [comment]
Awesome.  Thanks for your help!
