### ISSUE TITLE
Getting the markup of a text message doesn't work corrently for emojis

### ISSUE THREAD

**Issue by DerGenaue** [OllieTerrance/SkPy#92]
Emojis are represented by Skype using `<ss>` - Tags
The markup formatted of the text-messages unfortunately recognizes a `<s.*` and interprets it as a strikethrough; resulting in `:D` becoming `~:D~`

Fix:
eg. msg.py line ~342 replace all `</?ss.*?>` with nothing

**Comment by OllieTerrance** [comment]
Let's just use `\b` boundaries in the regexes to ensure we match the exact tag we want.
