### ISSUE TITLE
New Skype release in Sept 2018 - will SkPy still work afterwards?

### ISSUE THREAD

**Issue by idolezel** [OllieTerrance/SkPy#94]
Good morning,

recently I found a post from the Skype team: 

**Upgrade to the latest version of Skype for desktop**
https://blogs.skype.com/news/2018/07/16/upgrade-to-the-latest-version-of-skype-for-desktop/?eu=true

From September 2018, new version of Skype will be released. According to that post: "As we roll out improvements, there comes a time when we must shut down older services and application versions."

I am not sure if this affects also Skype HTTP API. I did not find any closer info. Is there any chance you can predict SkPy will be still functional after September 2018? It really is a great library.

Thank you in advance,

Michal

**Comment by OllieTerrance** [comment]
As that page says, it's specific to the legacy _desktop_ clients that predate the new cloudy stuff (specifically, they're the last clients to support P2P chats, which aren't supported by any cloud-only clients).

SkPy's future is dependent on Skype for Web, which will hopefully see no changes following the desktop client end-of-life, but as always, there could be breaking changes at any time.
