### ISSUE TITLE
Couldn't read group message with group name: 400 responded

### ISSUE THREAD

**Issue by ln2khanal** [OllieTerrance/SkPy#96]
I want to retrieve group messages using group names. Couldn't do it because response is of 400 type.

### Steps to reproduce
> Create a group
> Try to retrieve the group messages. Tried with "19:My Skype Group Name"

### Result or traceback
```message couldn't be read, ('400 response from GET https://hk2-2-client-s.gateway.messenger.live.com/v1/users/ME/conversations/<My Skype Group Name>', <Response [400]>)```

**Comment by OllieTerrance** [comment]
> Tried with "19:My Skype Group Name"

Uh, why?

Group chat topics are not identifiers -- they are not unique, not required.  You should either use identifiers if you have them (`19:abc...def@thread.skype`), or loop over [`Skype.chats`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChats) and check each group conversation's [`topic`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat.topic) attribute (note that `SkypeSingleChat` does not provide this attribute, do an instance check first).
