### ISSUE TITLE
how to avoid auth rate limit in search 

### ISSUE THREAD

**Issue by aymanone** [OllieTerrance/SkPy#98]
i need a way to search from 5000 to 10000 phone numbers in a day
but skype won't allow that
is there any way in windows i can avoid that 
i don't have static ip in my country
we don't have static ip in general

### Account type
microsoft account

**Comment by OllieTerrance** [comment]
That's unlikely to be acceptable under Skype's Terms of Service, and such rate limits likely exist in order to avoid behaviour such as this.
